// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNb_YLjcHoPByAN7iy1x199zf71ncZUEQ',
    appId: '1:548084257282:web:b8c8c3757cd3d75e068d1b',
    messagingSenderId: '548084257282',
    projectId: 'pricer-ee440',
    authDomain: 'pricer-ee440.firebaseapp.com',
    storageBucket: 'pricer-ee440.firebasestorage.app',
    measurementId: 'G-42K5247YKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DNlfA-9iQtux0MjL1HoUd_bomTMOBhs',
    appId: '1:548084257282:android:d6f6684ed712d2c4068d1b',
    messagingSenderId: '548084257282',
    projectId: 'pricer-ee440',
    storageBucket: 'pricer-ee440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrMASWLCuBq3J48hkz9X83ni7I4Y-3EY',
    appId: '1:548084257282:ios:a15ef4d59a63d627068d1b',
    messagingSenderId: '548084257282',
    projectId: 'pricer-ee440',
    storageBucket: 'pricer-ee440.firebasestorage.app',
    iosBundleId: 'com.pricer.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrMASWLCuBq3J48hkz9X83ni7I4Y-3EY',
    appId: '1:548084257282:ios:21be68c915bfb264068d1b',
    messagingSenderId: '548084257282',
    projectId: 'pricer-ee440',
    storageBucket: 'pricer-ee440.firebasestorage.app',
    iosBundleId: 'com.example.pricerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNb_YLjcHoPByAN7iy1x199zf71ncZUEQ',
    appId: '1:548084257282:web:d0cac417fa8cb0e9068d1b',
    messagingSenderId: '548084257282',
    projectId: 'pricer-ee440',
    authDomain: 'pricer-ee440.firebaseapp.com',
    storageBucket: 'pricer-ee440.firebasestorage.app',
    measurementId: 'G-8L5D42PB62',
  );
}