const { spawnSync } = require('node:child_process');

const testFiles = [
  'tests/phase_1_data_backbone.test.js',
  'tests/phase_2_matching.test.js',
  'tests/phase_3_core_flow.test.js',
  'tests/phase_3_5_aggregation.test.js',
  'tests/phase_4_query_engine_and_sync.test.js',
  'tests/phase_5_flutter_app.test.js',
  'tests/phase_5_5_ui_and_growth.test.js',
  'tests/phase_5_6_localization.test.js',
  'tests/phase_6_production_pipeline.test.js',
  'tests/phase_6_store_locations.test.js',
  'tests/phase_6_store_geocoding.test.js',
  'tests/phase_6_location_availability.test.js',
  'tests/phase_6_saved_user_locations.test.js',
  'tests/phase_6_location_review.test.js',
  'tests/phase_7_demand_intelligence.test.js',
  'tests/phase_8_best_basket.test.js',
  'tests/phase_9_watchlist_intelligence.test.js',
  'tests/phase_10_monetization.test.js',
  'tests/phase_11_production_persistence.test.js',
  'tests/phase_12_search_quality.test.js',
  'tests/phase_15_hyper_rich_enrichment.test.js',
  'tests/phase_15_1_enrichment_readers.test.js',
  'tests/phase_15_2_product_api.test.js',
  'tests/phase_15_3_shopping_list_resolution.test.js',
  'tests/phase_15_4_basket_input_planner.test.js',
  'tests/phase_15_6_diet_attribute_normalization.test.js',
  'tests/phase_15_7_expanded_diet_attribute_aliases.test.js',
  'tests/phase_16_0_price_lookup.test.js',
  'tests/phase_16_1_basket_optimizer.test.js',
  'tests/phase_16_2_multi_store_optimizer.test.js',
  'tests/phase_16_3_basket_explanation.test.js',
  'tests/phase_16_4_convenience_scoring.test.js',
  'tests/phase_16_5_basket_quality.test.js',
  'tests/phase_16_6_basket_analytics.test.js',
  'tests/phase_16_7_basket_health.test.js',
  'tests/phase_17_saved_shopping_lists.test.js',
  'tests/phase_17_1_persistent_lists.test.js',
  'tests/phase_17_2_watchlist_tracker.test.js',
  'tests/phase_17_3_deal_detection.test.js',
  'tests/phase_17_4_market_trends.test.js',
  'tests/phase_17_5_home_summary.test.js',
  'tests/phase_18_7_market_gap_detection.test.js',
  'tests/phase_20_1_local_gap.test.js',
  'tests/phase_20_2_chain_gap.test.js',
  'tests/phase_20_3_market_opportunity_reports.test.js',
  'tests/phase_20_4_merchant_insight_api.test.js',
  'tests/phase_20_5_internal_access_guard.test.js',
  'tests/phase_20_6_internal_insights_dashboard.test.js',
  'tests/db1_postgres_foundation.test.js',
  'tests/db2_usda_macro_import.test.js',
  'tests/db2_5_usda_clustering.test.js',
  'tests/db2_5_usda_cluster_batch.test.js',
  'tests/db2_5_usda_cluster_reports.test.js',
  'tests/db2_5_usda_cluster_materialization.test.js',
  'tests/db2_5_usda_cluster_review.test.js',
  'tests/db2_5_ingredient_nutrition_mappings.test.js',
  'tests/db3a_canonical_ingredients.test.js',
  'tests/db3b_ingredient_reports.test.js',
  'tests/db3c_ingredient_nutrition_profiles.test.js',
  'tests/db3d_ingredient_nutrition_profile_review.test.js',
  'tests/db3e_ingredient_product_equivalence.test.js',
  'tests/db4a_canonical_recipes.test.js',
  'tests/db4b_recipe_nutrition_profiles.test.js',
  'tests/db4c_recipe_nutrition_profile_review.test.js',
  'tests/db4d_recipe_quality_reports.test.js',
  'tests/db5a_recipe_ingest_staging.test.js',
  'tests/db5b_recipe_llm_extraction.test.js',
  'tests/db5c_recipe_promotion.test.js',
  'tests/ux1_user_food_profiles.test.js',
  'tests/ux2_recipe_feedback.test.js',
  'tests/prof1_user_taste_profiles.test.js',
  'tests/plan1_meal_planner.test.js',
  'tests/plan2a_meal_plan_requirements.test.js',
  'tests/plan2a1_inventory_adjusted_requirements.test.js',
  'tests/plan2b_product_candidates.test.js',
  'tests/plan2c_meal_plan_basket_optimizer.test.js',
  'tests/plan2d_meal_plan_shopping_orchestrator.test.js',
  'tests/app1_meal_planning_api.test.js',
  'tests/inventory1_user_inventory.test.js',
  'tests/phase_m0_ingredient.test.js',
  'tests/phase_m0_conversion.test.js',
  'tests/phase_m0_mapping.test.js',
];

let failed = 0;

for (const testFile of testFiles) {
  const result = spawnSync(process.execPath, [testFile], {
    stdio: 'inherit',
  });

  if (result.status !== 0) {
    failed += 1;
  }
}

if (failed > 0) {
  process.exitCode = 1;
}
