const { buildEnrichment, detectNameDrift } = require('./phase1/enrichment');
const { computeSnapshotId, computeSourceProductId } = require('./phase1/ids');
const {
  buildRawSnapshotRecord,
  importDailySnapshotFile,
  importDailySnapshotText,
  parseSnapshotRows,
} = require('./phase1/importer');
const {
  FirestoreDataBackboneStore,
  COLLECTION_DOCUMENT_IDS,
  DATA_BACKBONE_COLLECTIONS,
  JsonFileDataBackboneStore,
  InMemoryDataBackboneStore,
  buildDocumentId,
  createEmptyDataBackbone,
  createRuntimeDataBackboneStore,
  getEnrichmentByFingerprint,
  resolveCollectionName,
  resolveRuntimeStoreConfig,
  resolveStoreBackend,
  storeEnrichment,
  withRuntimeReadContext,
} = require('./phase1/store');
const { buildCanonicalEn } = require('./phase1_5/canonical_en');
const { buildDisplayEn, buildEnglishMetadata } = require('./phase1_5/display_builder');
const { translateDisplayEn } = require('./phase1_5/translator');
const { upgradeEnrichmentToEnglish } = require('./phase1_5/upgrade_enrichment');
const { upgradeTranslations } = require('./phase1_5/upgrade_translations');
const { aggregateCurrentPrices } = require('./phase2/aggregate');
const { detectAmbiguity } = require('./phase2/ambiguity');
const { filterCandidates, inferCategoryCodes, inferProductType } = require('./phase2/filter');
const { matchQueryAgainstState, matchSingleItem } = require('./phase2/matcher');
const { normalizeInput, parseQueryItem, splitQueryItems, tokenizeInput } = require('./phase2/normalize');
const { scoreCandidate } = require('./phase2/score');
const { handleQueryServiceRequest, queryPriceComparison } = require('./phase2/service');
const { aiDisambiguate } = require('./phase3/ai_disambiguator');
const { collectFeedback } = require('./phase3/feedback_collector');
const { generateDeterministicEmbedding, generateEmbeddingRecord } = require('./phase3/embedding_generator');
const { runEmbeddingGenerationJob, runSemanticEnrichmentJob } = require('./phase3/jobs');
const { buildSemanticProfile } = require('./phase3/semantic_enricher');
const { buildDailyAggregation } = require('./phase3_5/aggregator');
const { buildCategoryDailyAggregates } = require('./phase3_5/category_aggregator');
const { runDailyAggregation } = require('./phase3_5/job');
const { buildProductDailyPrices } = require('./phase3_5/product_aggregator');
const { getCategoryTrends, getProductHistory } = require('./phase3_5/service');
const { applyConstraintFilters } = require('./phase4/constraint_filters');
const { executeQueryPlan } = require('./phase4/query_executor');
const { parseQuery } = require('./phase4/query_parser');
const { buildQueryPlan } = require('./phase4/query_planner');
const { rankQueryResults } = require('./phase4/ranker');
const { handleQueryEngineRequest, queryEngine } = require('./phase4/service');
const { buildAnalyticsEvent, trackAnalyticsEvent, trackQueryAnalytics } = require('./phase6/analytics');
const { detectWatchlistPriceDrops, sendWatchlistAlerts } = require('./phase6/alerts');
const {
  applyEffectiveCanonicalDecisions,
  buildCanonicalDisambiguationPromptPayload,
  isLlmDisambiguationEnabled,
  parseCanonicalDisambiguationModelPayload,
  recordHumanCanonicalDisambiguationDecision,
  requestCanonicalDisambiguationBatch,
  runCanonicalDisambiguationAdjudication,
  getEffectiveCanonicalDisambiguationDecision,
  summarizeCanonicalDisambiguationReviewState,
  validateCanonicalDisambiguationDecision,
  validateCanonicalDisambiguationResponse,
} = require('./phase6/disambiguation');
const { backfillCanonicalEmbeddings, isEmbeddingApiConfigured, requestRemoteEmbedding } = require('./phase6/embeddings');
const { createFcmNotifier, isFcmConfigured } = require('./phase6/fcm');
const { chooseCandidateWithGrok, isGrokConfigured, resolveAmbiguityWithGrok } = require('./phase6/grok');
const {
  PRODUCT_QUALITY_STATUS,
  PRODUCT_QUARANTINE_SOURCE,
  classifyProductQualityReasons,
  isDataQualityQuarantined,
  summarizeProductQualityReasons,
  validateCanonicalProductRecord,
  validateCurrentOfferRecord,
  validateProductName,
  validateSourceProductRecord,
  validateSourceRowForImport,
} = require('./phase6/product_validation');
const {
  buildCanonicalDisambiguationFingerprint,
  buildCanonicalDisambiguationQueueRecord,
  buildCanonicalProductKey,
  buildCanonicalizationState,
  buildIngestRun,
  getCanonicalDisambiguationDecisionByFingerprint,
  importDailySnapshotCsvStream,
  importDailySnapshotZip,
  runCanonicalDisambiguationDryRun,
  syncCanonicalDisambiguationArtifacts,
  upsertCanonicalDisambiguationDecision,
} = require('./phase6/ingest');
const {
  buildSnapshotZipUrl,
  downloadSnapshotZip,
  listSnapshotEntries,
  openSnapshotEntryStream,
  openSnapshotEntryStreamByName,
  parseSnapshotEntryMetadata,
  resolveLatestAvailableSnapshotDate,
} = require('./phase6/kolkostruva_client');
const {
  STORE_LOCATION_RULES_VERSION,
  STORE_LOCATION_SOURCE,
  buildRetailerLocationCandidate,
  buildRetailerLocationId,
  buildRetailerLocationsFromState,
  parseStoreLocationText,
} = require('./phase6/store_locations');
const {
  DEFAULT_GEOCODING_PROVIDER,
  GEOCODING_RULES_VERSION,
  GEOCODING_STATUSES,
  MANUAL_ADDRESS_GEOCODING_RULES_VERSION,
  MANUAL_ADDRESS_GEOCODING_STATUSES,
  buildGeocodeId,
  buildGeocodingCacheKey,
  buildGeocodingQueryText,
  buildManualAddressGeocodeId,
  buildManualAddressGeocodingCacheKey,
  buildManualAddressGeocodingQueryText,
  createFakeGeocodingProvider,
  geocodeManualAddress,
  geocodeManualAddressInState,
  geocodeRetailerLocations,
  geocodeRetailerLocationsInState,
  handleManualAddressGeocodeRequest,
} = require('./phase6/geocoding');
const {
  ALLOWED_LOCATION_AVAILABILITY_SORTS,
  DEFAULT_COORDINATE_MODE,
  LOCATION_COORDINATE_MODES,
  LOCATION_AVAILABILITY_STATUSES,
  MAX_LIMIT: MAX_LOCATION_AVAILABILITY_LIMIT,
  MAX_RADIUS_KM,
  buildLocationAwareOffers,
  findNearestProductAvailability,
  handleNearestProductAvailabilityRequest,
  haversineDistanceKm,
  resolveDefaultCoordinateMode,
} = require('./phase6/location_availability');
const {
  ADMIN_IDENTITY_HEADERS,
  HIGH_REUSE_THRESHOLD,
  LOCATION_REVIEW_RULES_VERSION,
  LOCATION_REVIEW_STATUSES,
  LOW_CONFIDENCE_THRESHOLD,
  REVIEWED_COORDINATE_PRECEDENCE_POLICY,
  REVIEWED_COORDINATE_DEFAULT_SWITCH_CRITERIA,
  REVIEWED_COORDINATE_ROLLOUT_DIAGNOSTICS_RULES_VERSION,
  REVIEWED_LOCATION_COORDINATE_RULES_VERSION,
  buildLocationReviewCandidateId,
  buildReviewedCoordinateSourceIdentity,
  buildReviewedLocationCoordinateId,
  buildReviewedCoordinateDiagnostics,
  buildReviewedCoordinateRolloutDiagnostics,
  buildLocationReviewCandidates,
  buildLocationReviewCandidatesInState,
  compareLocationReviewCandidates,
  handleGetLocationReviewCandidateRequest,
  handleGetReviewedLocationCoordinateRequest,
  handleListLocationReviewCandidatesRequest,
  handleListReviewedLocationCoordinatesRequest,
  handleReviewLocationCandidateRequest,
  handleReviewedCoordinateDiagnosticsRequest,
  handleReviewedCoordinateRolloutDiagnosticsRequest,
  listReviewedLocationCoordinates,
  publishReviewedLocationCoordinates,
  publishReviewedLocationCoordinatesInState,
  reviewLocationCandidate,
  reviewLocationCandidateInState,
} = require('./phase6/location_review');
const {
  SAVED_LOCATION_LABELS,
  SAVED_LOCATION_SORTS,
  SAVED_LOCATION_SOURCES,
  buildSavedUserLocationId,
  deleteSavedUserLocation,
  handleDeleteSavedUserLocationRequest,
  handleListSavedUserLocationsRequest,
  handleUpsertSavedUserLocationRequest,
  listSavedUserLocations,
  resolveLocationForSearch,
  upsertSavedUserLocation,
} = require('./phase6/saved_user_locations');
const {
  ADMIN_INGEST_JOB_STATUSES,
  ADMIN_INGEST_SOURCE_TYPES,
  DEFAULT_HISTORICAL_TARGET_COLLECTIONS,
  HISTORICAL_CURRENT_READ_MODEL_COLLECTIONS,
  buildAdminIngestJobId,
  buildAdminIngestJobRecord,
  buildHistoricalIngestCommandPreview,
  createPlannedAdminIngestJob,
  getAdminIngestJob,
  handleCreateAdminIngestJobRequest,
  handleGetAdminIngestJobRequest,
  handleListAdminIngestJobsRequest,
  handlePlanAdminIngestRequest,
  listAdminIngestJobs,
  planHistoricalIngest,
} = require('./phase6/admin_ingest_jobs');
const {
  DEFAULT_INCREMENTAL_EVENT_POLICY,
  DEFAULT_INCREMENTAL_HIGH_WRITE_THRESHOLD,
  INCREMENTAL_INGEST_RULES_VERSION,
  buildCurrentOfferFingerprint,
  buildCurrentOfferFingerprints,
  buildCompactCurrentOfferBaselineRecord,
  buildCompactCurrentOfferBaselineRecords,
  buildRichCurrentOfferBaselineRecord,
  buildRichCurrentOfferBaselineRecords,
  buildOfferChangeEvents,
  buildIncrementalWriterPlan,
  buildSnapshotManifest,
  changedRowsForWriter,
  diffCurrentOffers,
  normalizeIncrementalEventPolicy,
} = require('./phase6/incremental_ingest');
const { runDailyProductionPipeline } = require('./phase6/jobs');
const { appendPipelineLog, createPipelineLog, recordPipelineLog } = require('./phase6/logging');
const { buildDailyIngestSchedule, shouldRunIngestForDate } = require('./phase6/scheduler');
const { rebuildDemandAggregates } = require('./phase7/aggregator');
const {
  DEMAND_EMBEDDING_MODEL,
  generateDemandEmbedding,
  rebuildDemandClusters,
  rebuildDemandEmbeddings,
} = require('./phase7/clustering');
const {
  buildDemandKey,
  buildDemandLogRecord,
  captureManualDemandFeedback,
  captureUnmatchedQuery,
} = require('./phase7/demand_logger');
const { runDemandIntelligenceJobs } = require('./phase7/jobs');
const {
  getTopDemand,
  getTrendingDemand,
  handleCantFindThisRequest,
  handleGetTopDemandRequest,
  handleGetTrendingDemandRequest,
} = require('./phase7/service');
const { DEFAULT_BASKET_LIMITS, DEFAULT_PREFERENCE_WEIGHTS } = require('./phase8/constants');
const { optimizeBasket, resolveLimits, resolvePreferences } = require('./phase8/optimizer');
const { handleOptimizeBasketRequest } = require('./phase8/service');
const {
  getTierFeatures,
  hasActivePremiumEntitlement,
  resolveUserTier,
  syncRevenueCatEntitlement,
} = require('./phase10/entitlements');
const {
  handleGetEntitlementStatusRequest,
  handleSyncRevenueCatEntitlementRequest,
} = require('./phase10/service');
const {
  buildCanonicalQueryObject,
  buildCanonicalTermRecord,
  buildSynonymRecord,
  levenshteinDistance,
  normalizeSearchText,
  tokenizeSearchText,
} = require('./phase12/canonicalization');
const {
  CATEGORY_TREE,
  CANONICAL_SEMANTIC_V3_PROMPT_VERSION,
  CANONICAL_SEMANTIC_V3_VERSION,
  ENRICHMENT_PROMPT_VERSION,
  RICH_ALLOWED_KEYS,
  RICH_CANONICAL_ENRICHMENT_VERSION,
  RICH_CANONICAL_PROMPT_VERSION,
  buildCanonicalSemanticV3BatchPrompt,
  buildCanonicalSemanticV3JsonSchema,
  buildEnrichmentPrompt,
  buildRichCanonicalEnrichmentBatchPrompt,
  extractExplicitDietAndAttributeTags,
  isLlmEnrichmentEnabled,
  normalizeDietAndAttributeTags,
  requestCanonicalEnrichment,
  syncCanonicalEnrichmentArtifacts,
  validateCanonicalSemanticV3BatchResponse,
  validateCanonicalSemanticV3BatchResponseDetailed,
  validateCanonicalSemanticV3Enrichment,
  validateEnrichmentResponse,
  validateRichCanonicalEnrichmentBatchResponse,
  validateRichCanonicalEnrichmentBatchResponseDetailed,
  validateRichCanonicalEnrichmentResponse,
} = require('./phase15/enrichment');
const {
  PILOT_ENRICHMENT_VERSION,
  PILOT_GROUPS,
  buildBatchEnrichmentPrompt,
  buildEnrichmentLlmProviderConfig,
  buildLlmRetryConfig,
  buildPilotConfig,
  buildProviderErrorSummary,
  buildProviderResponseFormat,
  canonicalNameHash,
  requestCanonicalEnrichmentBatch,
  resolvePilotEnrichmentVersion,
  runCanonicalEnrichmentHealthcheck,
  runCanonicalEnrichmentPilot,
  selectEnrichmentPilotCandidates,
} = require('./phase15/enrichment_pilot');
const {
  SEMANTIC_REGISTRY_DOMAINS,
  buildFailedEnrichmentResponseRecord,
  buildRegistryContext,
  buildSeedSemanticTermRegistry,
  createSemanticProposalId,
  createSemanticTermId,
  seedSemanticTermRegistry,
  writeRegistryProposalsFromActions,
} = require('./phase15/semantic_registry');
const {
  ATTRIBUTE_VOCABULARY,
  DIET_TAG_VOCABULARY,
  normalizeDietOrAttributeTag,
} = require('./phase15/diet_attribute_normalization');
const {
  ENRICHMENT_FILTER_FIELDS,
  LAYER_SELECTIONS,
  buildCanonicalEnrichmentAnalytics,
  buildSearchPlan,
  getCanonicalProductViewById,
  listCanonicalProductViews,
  searchCanonicalProductViews,
} = require('./phase15/readers');
const {
  GROCERY_SYNONYM_CONCEPTS,
  buildGroceryQueryExpansion,
} = require('./phase15/search_synonyms');
const {
  PRICE_NORMALIZATION_RULES_VERSION,
  inferPriceNormalization,
} = require('./phase15/price_normalization');
const {
  DEFAULT_PRODUCT_LAYER_MODE,
  FACET_FIELDS,
  buildProductListItem,
  handleCanonicalProductFilterFacetsRequest,
  handleGetCanonicalProductRequest,
  handleGetEnrichmentAnalyticsSummaryRequest,
  handleSearchCanonicalProductsRequest,
  resolveRequestedLayerMode,
  searchCanonicalProductCatalog,
} = require('./phase15/service');
const {
  CONFIDENCE_LEVELS,
  DEFAULT_LIMIT_PER_ITEM,
  INTERNAL_SEARCH_LIMIT,
  MAX_ITEMS_PER_REQUEST,
  MAX_LIMIT_PER_ITEM,
  RESOLUTION_STATUSES,
  SCORE_THRESHOLDS,
  handleResolveShoppingListItemsRequest,
  resolveShoppingListItems,
} = require('./phase15/shopping_list');
const {
  ALLOWED_AMBIGUOUS_POLICIES,
  ALLOWED_UNRESOLVED_POLICIES,
  DEFAULT_PLANNER_OPTIONS,
  DEFAULT_REQUESTED_QUANTITY,
  buildBasketPlanFromResolvedItems,
  handleBuildBasketPlanRequest,
} = require('./phase15/basket_planner');
const {
  DEFAULT_PREFERENCE_CONFIDENCE_THRESHOLD,
  FAMILY_ATTRIBUTE_INTENTS,
  FAMILY_PREFERENCE_SOURCES,
  PRODUCT_FAMILY_DEFINITIONS,
  SHOPPING_INTENT_RULES_VERSION,
  buildUserProductFamilyPreferenceId,
  handleResolveShoppingIntentRequest,
  identifyProductFamilies,
  listUserProductFamilyPreferences,
  loadUserProductFamilyPreference,
  normalizeUserProductFamilyPreference,
  resolveShoppingIntent,
  upsertUserProductFamilyPreference,
} = require('./phase15/shopping_intent');
const {
  ALLOWED_PRICE_MODES,
  ALLOWED_PRICE_STATUSES,
  DEFAULT_CURRENCY,
  DEFAULT_LOOKUP_OPTIONS,
  MAX_LOOKUP_IDS,
  handleLookupCanonicalProductPricesRequest,
  lookupCanonicalProductPrices,
  lookupPricesForBasketPlan,
} = require('./phase16/price_lookup');
const {
  CURRENT_OFFERS_RULES_VERSION,
  buildCurrentOfferReadModel,
  buildCurrentOfferId,
  loadCanonicalCurrentOfferSummaries,
  loadCurrentOffersByCanonicalProductIds,
  loadCurrentOffersBySourceProductIds,
} = require('./phase16/current_offers');
const {
  ALLOWED_OPTIMIZER_AMBIGUOUS_POLICIES,
  ALLOWED_OPTIMIZER_STRATEGIES,
  ALLOWED_STALE_POLICIES,
  DEFAULT_OPTIMIZER_OPTIONS,
  applyBasketConvenienceScoring,
  buildBasketOptimizationExplanation,
  buildBasketQualityMetrics,
  buildGlobalBasketMetricsSummary,
  handleOptimizeBasketSingleStoreRequest,
  normalizeOptimizerOptions,
  optimizeBasketMultiStore,
  optimizeBasketSingleStore,
} = require('./phase16/basket_optimizer');
const {
  ALLOWED_BASKET_ANALYTICS_WINDOWS,
  DEFAULT_BASKET_ANALYTICS_LIMIT,
  buildBasketAnalyticsRecord,
  getBasketAnalyticsSummary,
  handleGetBasketAnalyticsSummaryRequest,
  persistBasketAnalyticsRecord,
  summarizeBasketAnalyticsRecords,
} = require('./phase16/basket_analytics');
const {
  BASKET_HEALTH_THRESHOLDS,
  buildBasketHealthAlerts,
  handleGetBasketHealthRequest,
} = require('./phase16/basket_health');
const {
  createSavedList,
  deleteSavedList,
  getSavedList,
  handleCreateSavedListRequest,
  handleDeleteSavedListRequest,
  handleGetSavedListRequest,
  handleListSavedListsRequest,
  handleOptimizeSavedListRequest,
  handleUpdateSavedListRequest,
  listSavedLists,
  normalizeOwnerContext,
  normalizeSavedListItems,
  optimizeSavedList,
  resolveOwnerContextFromRequest,
  updateSavedList,
} = require('./phase17/saved_lists');
const {
  addWatchlistItem,
  buildWatchlistPriceView,
  getWatchlistItem,
  handleAddWatchlistItemRequest,
  handleGetWatchlistItemRequest,
  handleListWatchlistItemsRequest,
  handleRemoveWatchlistItemRequest,
  handleUpdateWatchlistItemRequest,
  handleWatchlistPriceViewRequest,
  listWatchlistItems,
  removeWatchlistItem,
  updateWatchlistItem,
} = require('./phase17/watchlist');
const {
  EXPENSIVE_AVG_MULTIPLIER,
  GOOD_DEAL_AVG_MULTIPLIER,
  annotateOptimizerResultWithDeals,
  classifyProductDeal,
  handleDealCheckRequest,
  summarizeDeals,
} = require('./phase17/deals');
const {
  ALLOWED_MARKET_TREND_GROUPS,
  ALLOWED_MARKET_TREND_WINDOWS,
  MARKET_TREND_DOWN_THRESHOLD,
  MARKET_TREND_UP_THRESHOLD,
  buildMarketTrendSummary,
  handleMarketOverviewRequest,
  handleMarketTrendsRequest,
} = require('./phase17/market_trends');
const {
  DEFAULT_HOME_SUMMARY_LIMITS,
  MAX_HOME_SUMMARY_LIMIT,
  buildHomeSummary,
  handleHomeSummaryRequest,
  normalizeHomeSummaryOptions,
} = require('./phase17/home_summary');
const {
  ALLOWED_GAP_GROUPS,
  ALLOWED_GAP_WINDOWS,
  DEFAULT_GAP_SCORING_CONFIG,
  buildGapDetectionSummary,
  buildGapCoverageByChain,
  buildLocalityGapSummary,
  buildMarketOpportunityReports,
  buildMerchantCategoryInsights,
  buildMerchantChainInsights,
  buildMerchantInsightOpportunities,
  buildMerchantInsightOverview,
  buildMerchantLocalityInsights,
  buildGapSignalFromResolvedItem,
  buildGapSignalFromSearch,
  buildGapSignalFromWatchlist,
  buildGapSignalRecord,
  classifyGapType,
  classifyOpportunityType,
  handleGetGapDetectionRequest,
  handleGetGapCoverageByChainRequest,
  handleGetLocalityGapDetectionRequest,
  handleGetMarketOpportunityReportsRequest,
  handleGetMerchantCategoryInsightsRequest,
  handleGetMerchantChainInsightsRequest,
  handleGetMerchantInsightOpportunitiesRequest,
  handleGetMerchantInsightOverviewRequest,
  handleGetMerchantLocalityInsightsRequest,
  normalizeLocalityCode,
  persistGapSignal,
  persistGapSignals,
} = require('./phase18/gap_detection');
const {
  ALLOWED_INTERNAL_ANALYTICS_ROLES,
  INTERNAL_ANALYTICS_ROLE_HEADER,
  INTERNAL_ANALYTICS_TOKEN_ENV,
  INTERNAL_ANALYTICS_TOKEN_HEADER,
  PROTECTED_INTERNAL_ANALYTICS_ENDPOINTS,
  isInternalAnalyticsPath,
  requireInternalAnalyticsAccess,
} = require('./phase18/internal_access');
const {
  INTERNAL_INSIGHTS_DASHBOARD_ENDPOINTS,
  INTERNAL_INSIGHTS_DASHBOARD_PATH,
  buildInternalInsightsDashboardHtml,
  handleInternalInsightsDashboardRequest,
} = require('./phase18/internal_dashboard');
const {
  runSearchQualityFeedbackLoop,
  seedSearchQualityDefaults,
} = require('./phase12/feedback_loop');
const {
  buildWatchlistSummary,
  getWatchlistInsights,
  runWatchlistDailyEvaluation,
  setTargetPrice,
} = require('./phase9/intelligence');
const { runDailyWatchlistIntelligence, runWeeklyIntervalRecompute } = require('./phase9/jobs');
const { recomputeWatchlistRecurringPatterns } = require('./phase9/recurrence');
const {
  handleSetTargetPriceRequest,
  handleWatchlistInsightsRequest,
  handleWatchlistSummaryRequest,
} = require('./phase9/service');
const { syncFirestoreToSQL } = require('./sync/firestore_to_sql');
const { syncFirestoreToVector } = require('./sync/firestore_to_vector');
const { runSyncJobs } = require('./sync/jobs');
const {
  buildPostgresConfig,
  checkPostgresHealth,
  createPostgresPool,
  isPostgresConfigured,
  withPostgresClient,
} = require('./db/postgres');
const {
  checksumSql,
  ensureSchemaMigrationsTable,
  listMigrationFiles,
  loadAppliedMigrations,
  resolveDefaultMigrationsDir,
  runPostgresMigrations,
} = require('./db/migrations');
const {
  completeImportBatch,
  createImportBatch,
  getImportBatch,
  getSourceDataset,
  insertSourceFile,
  normalizeDataset,
  normalizeImportBatch,
  normalizeSourceFile,
  upsertSourceDataset,
} = require('./db/import_metadata_repository');
const {
  DEFAULT_INGREDIENT_GENERATION_METHOD,
  DEFAULT_INGREDIENT_RULES_VERSION,
  SUPPORTED_INGREDIENT_REVIEW_STATUSES,
  createIngredient: createCanonicalIngredient,
  deleteIngredient: deleteCanonicalIngredient,
  getIngredientById: getCanonicalIngredientById,
  getIngredientByKey,
  hydrateIngredientRow,
  listIngredientsByReviewStatus,
  normalizeAliasesJson,
  normalizeIngredientKey,
  normalizeIngredientRecord,
  searchIngredients: searchCanonicalIngredients,
  upsertIngredientByKey,
} = require('./db/ingredients/ingredient_repository');
const {
  DEFAULT_INGREDIENT_REPORT_LIMIT,
  buildIngredientFilter,
  buildIngredientInspectionReport,
  buildRecommendedIngredientReviewTargets,
  normalizeIngredientReportOptions,
} = require('./db/ingredients/ingredient_reports');
const {
  DEFAULT_PROFILE_CANDIDATE_LIMIT,
  PROFILE_CANDIDATE_METHOD,
  PROFILE_CANDIDATE_RULES_VERSION,
  buildIngredientNutritionProfileCandidates,
  fetchApprovedMappingsWithMacroNutrients,
  generateIngredientNutritionProfileCandidates,
  normalizeProfileCandidateOptions,
  upsertIngredientNutritionProfileCandidates,
} = require('./db/ingredients/ingredient_nutrition_profiles');
const {
  DEFAULT_PROFILE_REVIEW_LIMIT,
  SUPPORTED_PROFILE_REVIEW_DECISIONS,
  buildIngredientNutritionProfileId,
  buildProfileReviewEventId,
  getIngredientNutritionProfileCandidateDetail,
  listApprovedIngredientNutritionProfiles,
  listIngredientNutritionProfileCandidatesForReview,
  normalizeProfileReviewDecision,
  reviewIngredientNutritionProfileCandidate,
  validateProfileCandidateReviewTransition,
} = require('./db/ingredients/ingredient_nutrition_profile_review_service');
const {
  DEFAULT_INGREDIENT_PRODUCT_GENERATION_METHOD,
  INGREDIENT_PRODUCT_MAPPING_TYPES,
  INGREDIENT_PRODUCT_REVIEW_STATUSES,
  buildIngredientProductMappingId,
  buildProductCandidateId,
  insertProductCandidate,
  insertProductCandidates,
  listIngredientProductMappingsByIngredient,
  listProductsByIngredient,
  normalizeIngredientProductMapping,
  normalizeProductCandidate,
  reviewIngredientProductMapping,
  suggestIngredientProductMappings,
  upsertIngredientProductMapping,
  upsertIngredientProductMappings,
} = require('./db/products/ingredient_product_repository');
const {
  buildIngredientProductMappingSuggestions,
  buildProductCandidates,
  matchProductCandidateToIngredient,
  parseProductAttributes,
} = require('./db/products/ingredient_product_matching');
const {
  DEFAULT_USER_FOOD_PROFILE_GENERATION_METHOD,
  DEFAULT_USER_FOOD_PROFILE_RULES_VERSION,
  SUPPORTED_USER_FOOD_PROFILE_REVIEW_STATUSES,
  SUPPORTED_USER_FOOD_CONSTRAINT_TYPES,
  SUPPORTED_USER_FOOD_TARGET_TYPES,
  SUPPORTED_USER_FOOD_CONSTRAINT_SEVERITIES,
  SUPPORTED_USER_FOOD_PREFERENCE_TYPES,
  SUPPORTED_USER_FOOD_PREFERENCE_SOURCES,
  addOrUpdateUserEquipment,
  addOrUpdateUserFoodPreference,
  addUserFoodConstraint,
  buildUserEquipmentId,
  buildUserFoodConstraintId,
  buildUserFoodPreferenceId,
  buildUserFoodProfileId,
  createUserFoodProfile,
  deleteUserFoodProfile,
  getUserFoodProfileBundle,
  getUserFoodProfileById,
  getUserFoodProfileByUserId,
  listUserEquipment,
  listUserFoodConstraints,
  listUserFoodPreferences,
  normalizeKey: normalizeUserFoodKey,
  normalizeUserEquipmentRecord,
  normalizeUserFoodConstraintRecord,
  normalizeUserFoodPreferenceRecord,
  normalizeUserFoodProfileRecord,
  removeUserFoodConstraint,
  updateUserFoodNutritionTargets,
  upsertUserFoodProfileByUserId,
} = require('./db/users/user_food_profile_repository');
const {
  DEFAULT_EVENT_SCORES,
  SUPPORTED_RECIPE_FEEDBACK_EVENT_TYPES,
  SUPPORTED_RECIPE_FEEDBACK_EXTRACTION_METHODS,
  SUPPORTED_RECIPE_FEEDBACK_POLARITIES,
  SUPPORTED_RECIPE_FEEDBACK_SIGNAL_TYPES,
  SUPPORTED_RECIPE_FEEDBACK_SOURCES,
  aggregateFeedbackSummaryByProfile,
  aggregateFeedbackSummaryByRecipe,
  attachManualNoteSignals,
  buildRecipeFeedbackId,
  buildRecipeFeedbackSignalId,
  buildRecipeFeedbackSummary,
  deleteRecipeFeedbackEvent,
  getLatestFeedbackForProfileAndRecipe,
  getRecipeFeedbackById,
  getRecipeFeedbackSignalById,
  hydrateRecipeFeedbackEventRow,
  hydrateRecipeFeedbackSignalRow,
  listFeedbackByProfileId,
  listFeedbackByRecipeId,
  normalizeRecipeFeedbackRecord,
  normalizeRecipeFeedbackSignalRecord,
  recordRecipeCooked,
  recordRecipeCookedAgain,
  recordRecipeDismissed,
  recordRecipeFeedbackEvent,
  recordRecipeFeedbackNote,
  recordRecipeImpression,
  recordRecipeSaved,
  recordRecipeSwipeLeft,
  recordRecipeSwipeRight,
  recordRecipeSwipeUp,
} = require('./db/users/recipe_feedback_repository');
const {
  DEFAULT_TASTE_PROFILE_BUILD_LIMIT,
  DEFAULT_TASTE_PROFILE_GENERATION_METHOD,
  DEFAULT_TASTE_PROFILE_RULES_VERSION,
  FEEDBACK_EVENT_INFLUENCE,
  NOTE_SIGNAL_FAMILY_MAP,
  SUPPORTED_TASTE_PROFILE_SIGNAL_FAMILIES,
  SUPPORTED_TASTE_PROFILE_SOURCE_TYPES,
  buildTasteProfileConfidence,
  buildUserTasteProfileSignalSourceId,
  buildUserTasteProfileSnapshot,
  buildUserTasteProfileSnapshotId,
  buildUserTasteProfileSnapshots,
  classifyTasteProfileConfidence,
  computeUserTasteProfileSnapshot,
  feedbackEventInfluence,
  hydrateTasteProfileSignalSourceRow,
  hydrateTasteProfileSnapshotRow,
  listUserTasteProfileSignalSources,
  listUserTasteProfileSnapshots,
  normalizeTasteProfileBuildOptions,
  normalizeTasteProfileSignalSourceRecord,
  normalizeTasteProfileSnapshotRecord,
} = require('./db/users/user_taste_profile_engine');
const {
  SUPPORTED_INVENTORY_PERISHABILITY_CLASSES,
  SUPPORTED_INVENTORY_STORAGE_TYPES,
  SUPPORTED_INVENTORY_UPDATE_SOURCES,
  addInventoryItem,
  buildInventoryIdentityKey,
  buildInventoryItemId,
  buildUserInventoryId,
  buildUserInventoryKey,
  createUserInventory,
  deleteUserInventory,
  getInventoryItemById,
  getOrCreateUserInventoryByUserId,
  getUserInventoryById,
  getUserInventoryByUserId,
  hydrateInventoryItemRow,
  hydrateUserInventoryRow,
  listInventoryItems,
  mergeDuplicateInventoryItems,
  normalizeInventoryItemRecord,
  reduceInventoryItemQuantity,
  removeInventoryItem,
  updateInventoryItemQuantity,
} = require('./db/users/user_inventory_repository');
const {
  DEFAULT_RECIPE_GENERATION_METHOD,
  DEFAULT_RECIPE_RULES_VERSION,
  SUPPORTED_RECIPE_REVIEW_STATUSES,
  deleteRecipe: deleteCanonicalRecipe,
  getIngredientsByKeys,
  getRecipeById,
  getRecipeByKey,
  getRecipeDetail,
  listRecipesByReviewStatus,
  normalizeIngredientKey: normalizeIngredientKeyForRecipe,
  normalizeName: normalizeRecipeName,
  normalizeRecipeIngredientRecord,
  normalizeRecipeKey,
  normalizeRecipeRecord,
  normalizeRecipeStepRecord,
  searchRecipesByNormalizedTitle,
  upsertRecipeByKey,
  upsertRecipeIngredients,
  upsertRecipeSteps,
} = require('./db/recipes/recipe_repository');
const {
  DEFAULT_RECIPE_PROFILE_CANDIDATE_LIMIT,
  RECIPE_NUTRITION_PROFILE_METHOD,
  RECIPE_NUTRITION_PROFILE_RULES_VERSION,
  assignRecipeNutritionConfidence,
  buildRecipeNutritionProfileCandidateId,
  buildRecipeNutritionProfileCandidates,
  fetchRecipeNutritionProfileSourceRows,
  generateRecipeNutritionProfileCandidates,
  hydrateRecipeNutritionProfileCandidateRow,
  normalizeRecipeNutritionProfileCandidate,
  normalizeRecipeNutritionProfileOptions,
  summarizeMissingNutritionInputs,
  upsertRecipeNutritionProfileCandidates,
} = require('./db/recipes/recipe_nutrition_profiles');
const {
  DEFAULT_RECIPE_PROFILE_REVIEW_LIMIT,
  SUPPORTED_RECIPE_PROFILE_REVIEW_DECISIONS,
  buildRecipeNutritionProfileId,
  buildRecipeProfileReviewEventId,
  getRecipeNutritionProfileCandidateDetail,
  listApprovedRecipeNutritionProfiles,
  listRecipeNutritionProfileCandidatesForReview,
  normalizeRecipeProfileReviewDecision,
  reviewRecipeNutritionProfileCandidate,
  validateRecipeProfileCandidateReviewTransition,
} = require('./db/recipes/recipe_nutrition_profile_review_service');
const {
  DEFAULT_RECIPE_INGEST_GENERATION_METHOD,
  DEFAULT_RECIPE_INGEST_LIMIT,
  DEFAULT_RECIPE_INGEST_RULES_VERSION,
  SUPPORTED_RECIPE_INGEST_JOB_STATUSES,
  SUPPORTED_STAGED_INGREDIENT_REVIEW_STATUSES,
  SUPPORTED_STAGED_RECIPE_REVIEW_STATUSES,
  buildRecipeIngestJobId,
  buildStagedRecipeId,
  createRecipeIngestJob,
  deleteRecipeIngestStaging,
  getStagedRecipeDetail,
  insertStagedRecipeBundle,
  listStagedRecipes,
  normalizeRecipeIngestJobRecord,
  normalizeStagedIngredientRecord,
  normalizeStagedRecipeRecord,
  normalizeStagedStepRecord,
  searchStagedRecipes,
  updateStagedRecipeReviewStatus,
} = require('./db/recipes/recipe_ingest_staging_repository');
const {
  DEFAULT_RECIPE_EXTRACTION_GENERATION_METHOD,
  DEFAULT_RECIPE_EXTRACTION_LIMIT,
  DEFAULT_RECIPE_EXTRACTION_RULES_VERSION,
  buildStagedRecipeBundleFromExtraction,
  extractRecipeJobToStaging,
  extractRecipeJobsToStaging,
  fetchRecipeIngestJobs,
  fetchStagedRecipesForJob,
  isRecipeExtractionLlmConfigured,
  matchExtractedIngredient,
  matchExtractedIngredients,
  requestRecipeExtraction,
  updateRecipeIngestJobStatus,
} = require('./db/recipes/recipe_llm_extraction');
const {
  PROMOTION_METHOD,
  PROMOTION_RULES_VERSION,
  SUPPORTED_PROMOTION_DECISIONS,
  SUPPORTED_RECIPE_USABILITY_STATUSES,
  appendRecipePromotionHistory,
  buildIngredientGapId,
  buildPromotionHistoryId,
  classifyRecipeUsability,
  computeRecipePromotionMetrics,
  getRecipePromotionCandidateDetail,
  getStagedRecipeDetailByJobId,
  listRecipePromotionCandidates,
  promoteStagedRecipeToCanonical,
  reviewAndPromoteRecipe,
  upsertIngredientGapCandidate,
} = require('./db/recipes/recipe_ingest_promotion_service');
const {
  DEFAULT_RECIPE_QUALITY_REPORT_LIMIT,
  SUPPORTED_RECIPE_QUALITY_STATUSES,
  SUPPORTED_RECIPE_READINESS_STATUSES,
  buildRecipeQualityReport,
  determineRecipeReadinessStatus,
  normalizeRecipeQualityReportOptions,
} = require('./db/recipes/recipe_quality_reports');
const {
  DEFAULT_MEAL_PLAN_DAYS,
  DEFAULT_MEALS_PER_DAY,
  MEAL_PLAN_GENERATION_METHOD,
  MEAL_PLAN_RULES_VERSION,
  SCORE_WEIGHTS,
  SUPPORTED_MEAL_PLAN_MEAL_TYPES,
  averageSelectionScore,
  buildFallbackTasteProfile,
  buildMealPlanId,
  buildMealPlanItemId,
  buildMealPlanKey,
  buildMealTargets,
  generateMealPlan,
  normalizeMealPlanOptions,
  scoreRecipeCandidate,
} = require('./db/planner/meal_planner_engine');
const {
  MEAL_PLAN_REQUIREMENTS_GENERATION_METHOD,
  MEAL_PLAN_REQUIREMENTS_RULES_VERSION,
  SUPPORTED_MEAL_PLAN_REQUIREMENT_ADAPTER_STATUSES,
  aggregateMealPlanRequirementItems,
  buildMealPlanRequirementId,
  buildMealPlanRequirementItemId,
  buildMealPlanRequirementKey,
  buildMealPlanRequirements,
  determineAdapterStatus,
  estimateShoppingQuantity,
  hydrateRequirementItemRow,
  normalizeMealPlanRequirementOptions,
  summarizeMealPlanRequirementItems,
} = require('./db/planner/meal_plan_requirements_builder');
const {
  MEAL_PLAN_NET_REQUIREMENTS_GENERATION_METHOD,
  MEAL_PLAN_NET_REQUIREMENTS_RULES_VERSION,
  SUPPORTED_MEAL_PLAN_NET_INVENTORY_STATUSES,
  SUPPORTED_MEAL_PLAN_NET_REQUIREMENT_ADAPTER_STATUSES,
  buildInventoryCoverageIndex,
  buildMealPlanNetRequirementId,
  buildMealPlanNetRequirementItemId,
  buildMealPlanNetRequirementKey,
  buildMealPlanNetRequirements,
  determineInventoryStatus,
  determineNetRequirementAdapterStatus,
  hydrateNetRequirementItemRow,
  normalizeMealPlanNetRequirementOptions,
  summarizeMealPlanNetRequirementItems,
} = require('./db/planner/meal_plan_net_requirements_builder');
const {
  MEAL_PLAN_PRODUCT_CANDIDATE_GENERATION_METHOD,
  MEAL_PLAN_PRODUCT_CANDIDATE_RULES_VERSION,
  SUPPORTED_MEAL_PLAN_PRODUCT_CANDIDATE_STATUSES,
  buildMealPlanProductCandidateId,
  buildMealPlanProductCandidateSet,
  buildMealPlanProductCandidateSetId,
  buildMealPlanProductCandidateSetKey,
  buildProductCandidates: buildMealPlanProductCandidates,
  convertPackageSizeToGrams,
  determineMealPlanProductCandidateStatus,
  hydrateMealPlanProductCandidateRow,
  normalizeMealPlanProductCandidateOptions,
  resolveCanonicalProductId,
  summarizeMealPlanProductCandidates,
} = require('./db/planner/meal_plan_product_candidate_builder');
const {
  MEAL_PLAN_BASKET_OPTIMIZER_GENERATION_METHOD,
  MEAL_PLAN_BASKET_OPTIMIZER_RULES_VERSION,
  MEAL_PLAN_BASKET_OPTIMIZER_VERSION,
  SUPPORTED_MEAL_PLAN_OPTIMIZED_BASKET_ITEM_STATUSES,
  buildMealPlanOptimizedBasketId,
  buildMealPlanOptimizedBasketItemId,
  buildMealPlanOptimizerRunKey,
  buildSyntheticBasketPlan,
  buildSyntheticPriceLookup,
  hydrateMealPlanOptimizedBasketItemRow,
  hydrateMealPlanOptimizedBasketRow,
  normalizeMealPlanBasketOptimizerOptions,
  optimizeMealPlanBasket,
} = require('./db/planner/meal_plan_basket_optimizer_adapter');
const {
  MEAL_PLAN_SHOPPING_ORCHESTRATION_GENERATION_METHOD,
  MEAL_PLAN_SHOPPING_ORCHESTRATION_RULES_VERSION,
  SUPPORTED_MEAL_PLAN_SHOPPING_RUN_STATUSES,
  buildMealPlanShoppingRunId,
  buildMealPlanShoppingRunKey,
  buildMealPlanShoppingRunRecord,
  determineMealPlanShoppingRunStatus,
  hydrateMealPlanShoppingRunRow,
  normalizeMealPlanShoppingOrchestrationOptions,
  resolveMealPlanShoppingOrchestrationAdapter,
  runMealPlanShoppingOrchestration,
} = require('./db/planner/meal_plan_shopping_orchestrator');
const {
  getMealPlanDetail,
  getMealPlanOptimizedBasketDetail,
  getMealPlanShoppingRunDetail,
  handleGenerateMealPlanRequest,
  handleGetMealPlanOptimizedBasketRequest,
  handleGetMealPlanRequest,
  handleGetMealPlanShoppingRunRequest,
  handleRunMealPlanShoppingRequest,
  resolveMealPlanningApiAdapter,
} = require('./api/meal_planning_api');
const {
  parseRecipeExtractionJson,
  validateRecipeExtractionPayload,
} = require('./db/recipes/recipe_extraction_schema');
const {
  RECIPE_EXTRACTION_PROMPT_VERSION,
  buildRecipeExtractionPrompt,
} = require('./prompts/recipe_ingest/extract_recipe_v1');
const {
  USDA_MACRO_NUTRIENTS,
  USDA_MACRO_NUTRIENT_IDS,
  isUsdaMacroNutrientId,
} = require('./db/usda/macro_constants');
const {
  isCompleteCsvRecord,
  parseCsvRecord,
  readCsvRows,
} = require('./db/usda/csv_stream');
const {
  USDA_REQUIRED_FILES,
  buildUsdaDatasetId,
  resolveUsdaDatasetRoot,
  resolveUsdaFilePaths,
} = require('./db/usda/usda_schema');
const {
  completeUsdaImportRun,
  createUsdaImportRun,
  getUsdaFoodWithMacros,
  normalizeFood,
  normalizeFoodCategory,
  normalizeFoodNutrient,
  normalizeFoodPortion,
  normalizeMeasureUnit,
  normalizeNutrient,
  normalizeUsdaImportRun,
  upsertUsdaFoodCategories,
  upsertUsdaFoodNutrients,
  upsertUsdaFoodPortions,
  upsertUsdaFoods,
  upsertUsdaMeasureUnits,
  upsertUsdaNutrients,
} = require('./db/usda/usda_repository');
const {
  checksumFile,
  importCsvInBatches,
  importUsdaMacros,
  inspectSourceFile,
  registerSourceFiles,
} = require('./db/usda/usda_importer');
const {
  CLUSTERABLE_DATA_TYPES,
  USDA_CLUSTER_GENERATION_METHOD,
  USDA_CLUSTER_RULES_VERSION,
  buildCandidateKey,
  buildHardBoundarySignature,
  buildUsdaClusterCandidate,
  parseUsdaFoodDescription,
  scoreRepresentativeCandidate,
  splitUsdaDescription,
} = require('./db/usda/cluster_candidate_parser');
const {
  listUsdaFoodClusterCandidatesByKey,
  normalizeUsdaFoodClusterCandidate,
  upsertUsdaFoodClusterCandidates,
} = require('./db/usda/cluster_candidate_repository');
const {
  DEFAULT_USDA_CLUSTER_BATCH_SIZE,
  DEFAULT_USDA_CLUSTER_SOURCE_VERSION,
  fetchUsdaClusterFoodPage,
  generateUsdaClusterCandidatesBatch,
  loadMacroPresenceForFoods,
  normalizeClusterBatchOptions,
} = require('./db/usda/cluster_candidate_batch');
const {
  DEFAULT_USDA_CLUSTER_MIN_CONFIDENCE,
  DEFAULT_USDA_CLUSTER_REPORT_LIMIT,
  buildUsdaClusterCandidateInspectionReport,
  normalizeClusterReportOptions,
} = require('./db/usda/cluster_candidate_reports');
const {
  DEFAULT_USDA_CLUSTER_MATERIALIZATION_BATCH_SIZE,
  DEFAULT_USDA_CLUSTER_MATERIALIZATION_LIMIT,
  MATERIALIZATION_METHOD,
  buildClusterKey,
  buildProposedCluster,
  buildProposedMembers,
  compareRepresentativeCandidates,
  fetchClusterMaterializationCandidates,
  materializeUsdaClustersPreview,
  normalizeClusterMaterializationOptions,
  upsertUsdaFoodClusterMembers,
  upsertUsdaFoodClusters,
} = require('./db/usda/cluster_materialization_preview');
const {
  DEFAULT_CLUSTER_REVIEW_LIMIT,
  SUPPORTED_CLUSTER_REVIEW_DECISIONS,
  buildReviewEventId,
  getUsdaFoodClusterReviewDetail,
  listUsdaFoodClustersForReview,
  normalizeReviewDecision,
  reviewUsdaFoodCluster,
  validateReviewTransition: validateUsdaClusterReviewTransition,
} = require('./db/usda/cluster_review_service');
const {
  DEFAULT_MAPPING_SUGGESTION_LIMIT,
  MAPPING_SUGGESTION_METHOD,
  buildIngredientNutritionMappingSuggestions,
  fetchApprovedUsdaClustersForMapping,
  fetchPricerIngredientsForMapping,
  inferClusterState,
  matchClusterToIngredient,
  normalizeMappingSuggestionOptions,
  suggestIngredientNutritionMappings,
  upsertIngredientNutritionMappingSuggestions,
} = require('./db/usda/ingredient_nutrition_mapping_suggestions');
const {
  DEFAULT_MAPPING_REVIEW_LIMIT,
  SUPPORTED_MAPPING_REVIEW_DECISIONS,
  buildMappingReviewEventId,
  getIngredientNutritionMappingReviewDetail,
  listIngredientNutritionMappingsForReview,
  normalizeMappingReviewDecision,
  reviewIngredientNutritionMapping,
  validateMappingReviewTransition,
} = require('./db/usda/ingredient_nutrition_mapping_review_service');
const {
  MEAL_ACTIVE_STATUSES,
  MEAL_DEFAULT_PRICE_FALLBACK_CONFIDENCE,
  MEAL_MAPPING_TYPES,
  MEAL_MAPPING_TYPE_PRIORITIES,
  MEAL_RUNTIME_SAFE_INGREDIENT_FIELDS,
  MEAL_SUPPORTED_LOCALES,
  MEAL_UNIT_TYPES,
} = require('./meal/shared/constants');
const {
  buildIngredientCategoryRecord,
  buildIngredientFamilyRecord,
  buildIngredientRecord,
  getIngredientById,
  getIngredientCategoryById,
  getIngredientFamilyById,
  listIngredientCategories,
  listIngredientFamilies,
  listIngredients,
  upsertIngredient,
  upsertIngredientCategory,
  upsertIngredientFamily,
} = require('./meal/catalog/service');
const {
  buildIngredientPurchaseDemand,
  buildIngredientUnitRuleRecord,
  buildUnitConversionRecord,
  buildUnitRecord,
  convertEdibleQuantityToPurchase,
  convertIngredientQuantityToEdible,
  convertUnitValue,
  getIngredientUnitRuleByIngredientId,
  getUnitById,
  listUnits,
  seedDefaultMealUnits,
  upsertIngredientUnitRule,
  upsertUnit,
  upsertUnitConversion,
} = require('./meal/units/service');
const {
  buildProductIngredientMappingRecord,
  estimateIngredientCost,
  listIngredientPriceCandidates,
  listProductIngredientMappings,
  resolveBestProductIngredientMapping,
  upsertProductIngredientMapping,
} = require('./meal/bridge/service');

module.exports = {
  ADMIN_IDENTITY_HEADERS,
  ALLOWED_AMBIGUOUS_POLICIES,
  ALLOWED_UNRESOLVED_POLICIES,
  ALLOWED_PRICE_MODES,
  ALLOWED_PRICE_STATUSES,
  ALLOWED_MARKET_TREND_GROUPS,
  ALLOWED_MARKET_TREND_WINDOWS,
  ALLOWED_OPTIMIZER_AMBIGUOUS_POLICIES,
  ALLOWED_OPTIMIZER_STRATEGIES,
  ALLOWED_STALE_POLICIES,
  ALLOWED_BASKET_ANALYTICS_WINDOWS,
  ALLOWED_GAP_GROUPS,
  ALLOWED_GAP_WINDOWS,
  ALLOWED_INTERNAL_ANALYTICS_ROLES,
  ADMIN_INGEST_JOB_STATUSES,
  ADMIN_INGEST_SOURCE_TYPES,
  BASKET_HEALTH_THRESHOLDS,
  CURRENT_OFFERS_RULES_VERSION,
  aggregateCurrentPrices,
  aiDisambiguate,
  appendPipelineLog,
  applyBasketConvenienceScoring,
  applyConstraintFilters,
  backfillCanonicalEmbeddings,
  applyEffectiveCanonicalDecisions,
  buildAnalyticsEvent,
  buildBasketAnalyticsRecord,
  buildBasketHealthAlerts,
  buildBasketOptimizationExplanation,
  buildBasketPlanFromResolvedItems,
  buildBasketQualityMetrics,
  buildCanonicalQueryObject,
  buildCanonicalTermRecord,
  buildCategoryDailyAggregates,
  buildCanonicalEn,
  buildCanonicalDisambiguationFingerprint,
  buildCanonicalDisambiguationPromptPayload,
  buildCanonicalDisambiguationQueueRecord,
  buildCanonicalProductKey,
  buildAdminIngestJobId,
  buildAdminIngestJobRecord,
  buildCurrentOfferId,
  buildCurrentOfferFingerprint,
  buildCurrentOfferFingerprints,
  buildCompactCurrentOfferBaselineRecord,
  buildCompactCurrentOfferBaselineRecords,
  buildRichCurrentOfferBaselineRecord,
  buildRichCurrentOfferBaselineRecords,
  buildCurrentOfferReadModel,
  buildOfferChangeEvents,
  buildIncrementalWriterPlan,
  buildSnapshotManifest,
  changedRowsForWriter,
  diffCurrentOffers,
  DEFAULT_INCREMENTAL_EVENT_POLICY,
  DEFAULT_INCREMENTAL_HIGH_WRITE_THRESHOLD,
  INCREMENTAL_INGEST_RULES_VERSION,
  normalizeIncrementalEventPolicy,
  buildDailyAggregation,
  buildDailyIngestSchedule,
  buildDemandKey,
  buildDemandLogRecord,
  buildGapDetectionSummary,
  buildGapCoverageByChain,
  buildLocalityGapSummary,
  buildMarketOpportunityReports,
  buildMerchantCategoryInsights,
  buildMerchantChainInsights,
  buildMerchantInsightOpportunities,
  buildMerchantInsightOverview,
  buildMerchantLocalityInsights,
  buildGapSignalFromResolvedItem,
  buildGapSignalFromSearch,
  buildGapSignalFromWatchlist,
  buildGapSignalRecord,
  buildGlobalBasketMetricsSummary,
  buildHomeSummary,
  buildHistoricalIngestCommandPreview,
  buildInternalInsightsDashboardHtml,
  buildMarketTrendSummary,
  buildDisplayEn,
  buildCanonicalizationState,
  buildSavedUserLocationId,
  buildSynonymRecord,
  buildEnglishMetadata,
  buildEnrichment,
  buildGeocodeId,
  buildGeocodingCacheKey,
  buildGeocodingQueryText,
  buildManualAddressGeocodeId,
  buildManualAddressGeocodingCacheKey,
  buildManualAddressGeocodingQueryText,
  buildLocationAwareOffers,
  buildLocationReviewCandidateId,
  buildReviewedCoordinateDiagnostics,
  buildReviewedCoordinateRolloutDiagnostics,
  buildReviewedCoordinateSourceIdentity,
  buildReviewedLocationCoordinateId,
  buildLocationReviewCandidates,
  buildLocationReviewCandidatesInState,
  buildIngestRun,
  buildProductDailyPrices,
  buildQueryPlan,
  buildRawSnapshotRecord,
  buildSemanticProfile,
  buildSnapshotZipUrl,
  buildWatchlistSummary,
  captureManualDemandFeedback,
  captureUnmatchedQuery,
  chooseCandidateWithGrok,
  classifyGapType,
  classifyOpportunityType,
  collectFeedback,
  compareLocationReviewCandidates,
  computeSnapshotId,
  computeSourceProductId,
  createEmptyDataBackbone,
  createFakeGeocodingProvider,
  createFcmNotifier,
  createPipelineLog,
  COLLECTION_DOCUMENT_IDS,
  ATTRIBUTE_VOCABULARY,
  CATEGORY_TREE,
  CONFIDENCE_LEVELS,
  DEFAULT_BASKET_LIMITS,
  DEFAULT_BASKET_ANALYTICS_LIMIT,
  DEFAULT_CURRENCY,
  DEFAULT_CLUSTER_REVIEW_LIMIT,
  DEFAULT_GEOCODING_PROVIDER,
  DEFAULT_LIMIT_PER_ITEM,
  DEFAULT_LOOKUP_OPTIONS,
  DEFAULT_HOME_SUMMARY_LIMITS,
  DEFAULT_HISTORICAL_TARGET_COLLECTIONS,
  DEFAULT_GAP_SCORING_CONFIG,
  DEFAULT_OPTIMIZER_OPTIONS,
  DEFAULT_PLANNER_OPTIONS,
  DEFAULT_PRODUCT_LAYER_MODE,
  DEFAULT_PREFERENCE_WEIGHTS,
  DEFAULT_REQUESTED_QUANTITY,
  DEFAULT_USDA_CLUSTER_BATCH_SIZE,
  DEFAULT_USDA_CLUSTER_MATERIALIZATION_BATCH_SIZE,
  DEFAULT_USDA_CLUSTER_MATERIALIZATION_LIMIT,
  DEFAULT_USDA_CLUSTER_MIN_CONFIDENCE,
  DEFAULT_USDA_CLUSTER_REPORT_LIMIT,
  DEFAULT_USDA_CLUSTER_SOURCE_VERSION,
  DEFAULT_COORDINATE_MODE,
  MAX_LOCATION_AVAILABILITY_LIMIT,
  MAX_RADIUS_KM,
  DIET_TAG_VOCABULARY,
  DEMAND_EMBEDDING_MODEL,
  GEOCODING_RULES_VERSION,
  GEOCODING_STATUSES,
  HISTORICAL_CURRENT_READ_MODEL_COLLECTIONS,
  HIGH_REUSE_THRESHOLD,
  MANUAL_ADDRESS_GEOCODING_RULES_VERSION,
  MANUAL_ADDRESS_GEOCODING_STATUSES,
  LOCATION_COORDINATE_MODES,
  LOCATION_AVAILABILITY_STATUSES,
  LOCATION_REVIEW_RULES_VERSION,
  LOCATION_REVIEW_STATUSES,
  LOW_CONFIDENCE_THRESHOLD,
  REVIEWED_COORDINATE_DEFAULT_SWITCH_CRITERIA,
  REVIEWED_COORDINATE_PRECEDENCE_POLICY,
  REVIEWED_COORDINATE_ROLLOUT_DIAGNOSTICS_RULES_VERSION,
  REVIEWED_LOCATION_COORDINATE_RULES_VERSION,
  ALLOWED_LOCATION_AVAILABILITY_SORTS,
  ENRICHMENT_FILTER_FIELDS,
  detectAmbiguity,
  detectNameDrift,
  detectWatchlistPriceDrops,
  downloadSnapshotZip,
  executeQueryPlan,
  extractExplicitDietAndAttributeTags,
  FACET_FIELDS,
  fetchClusterMaterializationCandidates,
  fetchUsdaClusterFoodPage,
  FirestoreDataBackboneStore,
  DATA_BACKBONE_COLLECTIONS,
  filterCandidates,
  generateDemandEmbedding,
  generateDeterministicEmbedding,
  generateEmbeddingRecord,
  generateUsdaClusterCandidatesBatch,
  geocodeManualAddress,
  geocodeManualAddressInState,
  geocodeRetailerLocations,
  geocodeRetailerLocationsInState,
  findNearestProductAvailability,
  getCanonicalDisambiguationDecisionByFingerprint,
  getCanonicalProductViewById,
  getBasketAnalyticsSummary,
  getEffectiveCanonicalDisambiguationDecision,
  getEnrichmentByFingerprint,
  getTierFeatures,
  getCategoryTrends,
  getAdminIngestJob,
  getProductHistory,
  getTopDemand,
  getTrendingDemand,
  getWatchlistInsights,
  haversineDistanceKm,
  handleBuildBasketPlanRequest,
  handleCreateAdminIngestJobRequest,
  handleGetBasketAnalyticsSummaryRequest,
  handleGetBasketHealthRequest,
  handleGetGapDetectionRequest,
  handleGetGapCoverageByChainRequest,
  handleGetLocalityGapDetectionRequest,
  handleGetMarketOpportunityReportsRequest,
  handleGetMerchantCategoryInsightsRequest,
  handleGetMerchantChainInsightsRequest,
  handleGetMerchantInsightOpportunitiesRequest,
  handleGetMerchantInsightOverviewRequest,
  handleGetMerchantLocalityInsightsRequest,
  handleCreateSavedListRequest,
  handleDeleteSavedListRequest,
  handleGetSavedListRequest,
  handleDealCheckRequest,
  handleHomeSummaryRequest,
  handleInternalInsightsDashboardRequest,
  handleMarketOverviewRequest,
  handleMarketTrendsRequest,
  handleManualAddressGeocodeRequest,
  handleNearestProductAvailabilityRequest,
  handleLookupCanonicalProductPricesRequest,
  handleListSavedListsRequest,
  handleListSavedUserLocationsRequest,
  handleGetLocationReviewCandidateRequest,
  handleGetReviewedLocationCoordinateRequest,
  handleGetAdminIngestJobRequest,
  handleListAdminIngestJobsRequest,
  handleListLocationReviewCandidatesRequest,
  handleListReviewedLocationCoordinatesRequest,
  handleReviewLocationCandidateRequest,
  handleReviewedCoordinateDiagnosticsRequest,
  handleReviewedCoordinateRolloutDiagnosticsRequest,
  handleOptimizeBasketSingleStoreRequest,
  handleOptimizeSavedListRequest,
  handlePlanAdminIngestRequest,
  handleResolveShoppingIntentRequest,
  handleResolveShoppingListItemsRequest,
  handleCanonicalProductFilterFacetsRequest,
  handleGetCanonicalProductRequest,
  handleGetEntitlementStatusRequest,
  handleCantFindThisRequest,
  handleGetEnrichmentAnalyticsSummaryRequest,
  handleGetTopDemandRequest,
  handleGetTrendingDemandRequest,
  handleOptimizeBasketRequest,
  handleQueryEngineRequest,
  handleQueryServiceRequest,
  handleSearchCanonicalProductsRequest,
  handleSetTargetPriceRequest,
  handleSyncRevenueCatEntitlementRequest,
  handleUpdateSavedListRequest,
  handleUpsertSavedUserLocationRequest,
  handleWatchlistInsightsRequest,
  handleAddWatchlistItemRequest,
  handleGetWatchlistItemRequest,
  handleListWatchlistItemsRequest,
  handleRemoveWatchlistItemRequest,
  handleUpdateWatchlistItemRequest,
  handleWatchlistPriceViewRequest,
  handleWatchlistSummaryRequest,
  hasActivePremiumEntitlement,
  createPlannedAdminIngestJob,
  importDailySnapshotCsvStream,
  importDailySnapshotFile,
  importDailySnapshotText,
  importDailySnapshotZip,
  importCsvInBatches,
  importUsdaMacros,
  inferCategoryCodes,
  inferProductType,
  InMemoryDataBackboneStore,
  inspectSourceFile,
  isCompleteCsvRecord,
  isEmbeddingApiConfigured,
  isFcmConfigured,
  isGrokConfigured,
  isInternalAnalyticsPath,
  isLlmEnrichmentEnabled,
  isLlmDisambiguationEnabled,
  INTERNAL_SEARCH_LIMIT,
  INTERNAL_ANALYTICS_ROLE_HEADER,
  INTERNAL_ANALYTICS_TOKEN_ENV,
  INTERNAL_ANALYTICS_TOKEN_HEADER,
  INTERNAL_INSIGHTS_DASHBOARD_ENDPOINTS,
  INTERNAL_INSIGHTS_DASHBOARD_PATH,
  JsonFileDataBackboneStore,
  levenshteinDistance,
  LAYER_SELECTIONS,
  listCanonicalProductViews,
  listAdminIngestJobs,
  lookupCanonicalProductPrices,
  lookupPricesForBasketPlan,
  loadMacroPresenceForFoods,
  materializeUsdaClustersPreview,
  matchQueryAgainstState,
  matchSingleItem,
  MAX_ITEMS_PER_REQUEST,
  MAX_HOME_SUMMARY_LIMIT,
  MAX_LOOKUP_IDS,
  MAX_LIMIT_PER_ITEM,
  MATERIALIZATION_METHOD,
  MARKET_TREND_DOWN_THRESHOLD,
  MARKET_TREND_UP_THRESHOLD,
  SAVED_LOCATION_LABELS,
  SAVED_LOCATION_SORTS,
  SAVED_LOCATION_SOURCES,
  listSnapshotEntries,
  normalizeInput,
  normalizeDietAndAttributeTags,
  normalizeDietOrAttributeTag,
  normalizeOptimizerOptions,
  normalizeSearchText,
  openSnapshotEntryStream,
  openSnapshotEntryStreamByName,
  optimizeBasket,
  optimizeBasketMultiStore,
  optimizeBasketSingleStore,
  parseCsvRecord,
  parseStoreLocationText,
  parseQuery,
  parseQueryItem,
  parseCanonicalDisambiguationModelPayload,
  persistBasketAnalyticsRecord,
  persistGapSignal,
  persistGapSignals,
  PROTECTED_INTERNAL_ANALYTICS_ENDPOINTS,
  parseSnapshotRows,
  queryEngine,
  queryPriceComparison,
  rankQueryResults,
  recordHumanCanonicalDisambiguationDecision,
  recordPipelineLog,
  parseSnapshotEntryMetadata,
  resolveStoreBackend,
  resolveLocationForSearch,
  resolveDefaultCoordinateMode,
  planHistoricalIngest,
  rebuildDemandAggregates,
  rebuildDemandClusters,
  rebuildDemandEmbeddings,
  recomputeWatchlistRecurringPatterns,
  requestRemoteEmbedding,
  requestCanonicalEnrichment,
  requestCanonicalDisambiguationBatch,
  requireInternalAnalyticsAccess,
  publishReviewedLocationCoordinates,
  publishReviewedLocationCoordinatesInState,
  reviewLocationCandidate,
  reviewLocationCandidateInState,
  reviewUsdaFoodCluster,
  resolveUserTier,
  resolveAmbiguityWithGrok,
  resolveLatestAvailableSnapshotDate,
  resolveRequestedLayerMode,
  resolveLimits,
  resolvePreferences,
  resolveShoppingIntent,
  resolveShoppingListItems,
  RESOLUTION_STATUSES,
  runCanonicalDisambiguationAdjudication,
  runCanonicalDisambiguationDryRun,
  runDailyAggregation,
  runDailyProductionPipeline,
  buildDocumentId,
  resolveCollectionName,
  runDailyWatchlistIntelligence,
  runDemandIntelligenceJobs,
  runEmbeddingGenerationJob,
  runSemanticEnrichmentJob,
  runSearchQualityFeedbackLoop,
  runSyncJobs,
  runWatchlistDailyEvaluation,
  runWeeklyIntervalRecompute,
  scoreCandidate,
  SCORE_THRESHOLDS,
  GROCERY_SYNONYM_CONCEPTS,
  buildGroceryQueryExpansion,
  DEFAULT_PREFERENCE_CONFIDENCE_THRESHOLD,
  FAMILY_ATTRIBUTE_INTENTS,
  FAMILY_PREFERENCE_SOURCES,
  PRODUCT_FAMILY_DEFINITIONS,
  SHOPPING_INTENT_RULES_VERSION,
  buildUserProductFamilyPreferenceId,
  identifyProductFamilies,
  listUserProductFamilyPreferences,
  loadUserProductFamilyPreference,
  normalizeUserProductFamilyPreference,
  upsertUserProductFamilyPreference,
  buildSearchPlan,
  buildBatchEnrichmentPrompt,
  buildEnrichmentLlmProviderConfig,
  buildRichCanonicalEnrichmentBatchPrompt,
  buildPilotConfig,
  buildProviderErrorSummary,
  searchCanonicalProductViews,
  searchCanonicalProductCatalog,
  seedSearchQualityDefaults,
  sendWatchlistAlerts,
  requestCanonicalEnrichmentBatch,
  runCanonicalEnrichmentHealthcheck,
  runCanonicalEnrichmentPilot,
  selectEnrichmentPilotCandidates,
  setTargetPrice,
  shouldRunIngestForDate,
  storeEnrichment,
  summarizeDeals,
  buildPostgresConfig,
  buildRetailerLocationCandidate,
  buildRetailerLocationId,
  buildRetailerLocationsFromState,
  buildProductListItem,
  inferPriceNormalization,
  buildCanonicalEnrichmentAnalytics,
  checkPostgresHealth,
  checksumFile,
  checksumSql,
  completeImportBatch,
  completeUsdaImportRun,
  createImportBatch,
  createPostgresPool,
  createSavedList,
  createUsdaImportRun,
  deleteSavedList,
  deleteSavedUserLocation,
  handleDeleteSavedUserLocationRequest,
  splitQueryItems,
  syncCanonicalEnrichmentArtifacts,
  summarizeCanonicalDisambiguationReviewState,
  syncCanonicalDisambiguationArtifacts,
  syncFirestoreToSQL,
  syncFirestoreToVector,
  PRODUCT_QUALITY_STATUS,
  PRODUCT_QUARANTINE_SOURCE,
  classifyProductQualityReasons,
  isDataQualityQuarantined,
  summarizeProductQualityReasons,
  tokenizeInput,
  tokenizeSearchText,
  trackAnalyticsEvent,
  trackQueryAnalytics,
  translateDisplayEn,
  syncRevenueCatEntitlement,
  CANONICAL_SEMANTIC_V3_PROMPT_VERSION,
  CANONICAL_SEMANTIC_V3_VERSION,
  ENRICHMENT_PROMPT_VERSION,
  RICH_ALLOWED_KEYS,
  RICH_CANONICAL_ENRICHMENT_VERSION,
  RICH_CANONICAL_PROMPT_VERSION,
  PILOT_ENRICHMENT_VERSION,
  PILOT_GROUPS,
  SEMANTIC_REGISTRY_DOMAINS,
  PRICE_NORMALIZATION_RULES_VERSION,
  EXPENSIVE_AVG_MULTIPLIER,
  GOOD_DEAL_AVG_MULTIPLIER,
  upsertCanonicalDisambiguationDecision,
  upsertSavedUserLocation,
  upsertIngredient,
  upsertIngredientCategory,
  upsertIngredientFamily,
  upsertIngredientUnitRule,
  upsertProductIngredientMapping,
  upsertUnit,
  upsertUnitConversion,
  createRuntimeDataBackboneStore,
  resolveRuntimeStoreConfig,
  withRuntimeReadContext,
  addWatchlistItem,
  annotateOptimizerResultWithDeals,
  classifyProductDeal,
  ensureSchemaMigrationsTable,
  getImportBatch,
  getIngredientNutritionMappingReviewDetail,
  getSavedList,
  getSourceDataset,
  getWatchlistItem,
  getUsdaFoodClusterReviewDetail,
  getUsdaFoodWithMacros,
  insertSourceFile,
  isPostgresConfigured,
  isUsdaMacroNutrientId,
  listIngredientNutritionMappingsForReview,
  listMigrationFiles,
  listReviewedLocationCoordinates,
  listSavedLists,
  listSavedUserLocations,
  loadCanonicalCurrentOfferSummaries,
  loadCurrentOffersByCanonicalProductIds,
  loadCurrentOffersBySourceProductIds,
  listUsdaFoodClustersForReview,
  listWatchlistItems,
  loadAppliedMigrations,
  normalizeClusterBatchOptions,
  normalizeClusterMaterializationOptions,
  normalizeClusterReportOptions,
  normalizeDataset,
  normalizeLocalityCode,
  normalizeHomeSummaryOptions,
  normalizeFood,
  normalizeFoodCategory,
  normalizeFoodNutrient,
  normalizeFoodPortion,
  normalizeImportBatch,
  normalizeMeasureUnit,
  normalizeNutrient,
  normalizeOwnerContext,
  normalizeMappingReviewDecision,
  normalizeReviewDecision,
  normalizeSavedListItems,
  normalizeSourceFile,
  normalizeUsdaImportRun,
  reviewIngredientNutritionMapping,
  validateCanonicalDisambiguationDecision,
  validateCanonicalProductRecord,
  validateCurrentOfferRecord,
  validateMappingReviewTransition,
  validateReviewTransition: validateUsdaClusterReviewTransition,
  validateUsdaClusterReviewTransition,
  validateCanonicalDisambiguationResponse,
  validateEnrichmentResponse,
  validateCanonicalSemanticV3BatchResponse,
  validateCanonicalSemanticV3BatchResponseDetailed,
  validateCanonicalSemanticV3Enrichment,
  validateRichCanonicalEnrichmentBatchResponse,
  validateRichCanonicalEnrichmentBatchResponseDetailed,
  validateRichCanonicalEnrichmentResponse,
  validateProductName,
  validateSourceProductRecord,
  validateSourceRowForImport,
  upgradeEnrichmentToEnglish,
  upgradeTranslations,
  buildEnrichmentPrompt,
  buildCanonicalSemanticV3BatchPrompt,
  buildCanonicalSemanticV3JsonSchema,
  buildFailedEnrichmentResponseRecord,
  buildLlmRetryConfig,
  buildProviderResponseFormat,
  buildRegistryContext,
  buildSeedSemanticTermRegistry,
  canonicalNameHash,
  createSemanticProposalId,
  createSemanticTermId,
  buildWatchlistPriceView,
  resolveDefaultMigrationsDir,
  optimizeSavedList,
  removeWatchlistItem,
  resolvePilotEnrichmentVersion,
  resolveOwnerContextFromRequest,
  resolveUsdaDatasetRoot,
  resolveUsdaFilePaths,
  runPostgresMigrations,
  buildIngredientCategoryRecord,
  buildIngredientFamilyRecord,
  buildIngredientPurchaseDemand,
  buildIngredientRecord,
  buildIngredientUnitRuleRecord,
  buildProductIngredientMappingRecord,
  buildUnitConversionRecord,
  buildUnitRecord,
  updateWatchlistItem,
  buildUsdaDatasetId,
  updateSavedList,
  buildCandidateKey,
  buildClusterKey,
  buildIngredientNutritionMappingSuggestions,
  buildMappingReviewEventId,
  buildReviewEventId,
  seedSemanticTermRegistry,
  writeRegistryProposalsFromActions,
  buildHardBoundarySignature,
  buildProposedCluster,
  buildProposedMembers,
  buildUsdaClusterCandidate,
  buildUsdaClusterCandidateInspectionReport,
  compareRepresentativeCandidates,
  computeRecipePromotionMetrics,
  fetchApprovedUsdaClustersForMapping,
  fetchPricerIngredientsForMapping,
  convertEdibleQuantityToPurchase,
  convertIngredientQuantityToEdible,
  convertUnitValue,
  estimateIngredientCost,
  getIngredientById,
  getIngredientCategoryById,
  getIngredientFamilyById,
  getIngredientUnitRuleByIngredientId,
  getUnitById,
  inferClusterState,
  listIngredientCategories,
  listIngredientFamilies,
  listIngredientPriceCandidates,
  listIngredients,
  listProductIngredientMappings,
  listUnits,
  MEAL_ACTIVE_STATUSES,
  MEAL_DEFAULT_PRICE_FALLBACK_CONFIDENCE,
  MEAL_MAPPING_TYPES,
  MEAL_MAPPING_TYPE_PRIORITIES,
  MEAL_RUNTIME_SAFE_INGREDIENT_FIELDS,
  MEAL_SUPPORTED_LOCALES,
  MEAL_UNIT_TYPES,
  matchClusterToIngredient,
  resolveBestProductIngredientMapping,
  seedDefaultMealUnits,
  summarizeBasketAnalyticsRecords,
  SUPPORTED_CLUSTER_REVIEW_DECISIONS,
  DEFAULT_MAPPING_REVIEW_LIMIT,
  DEFAULT_MAPPING_SUGGESTION_LIMIT,
  DEFAULT_INGREDIENT_GENERATION_METHOD,
  DEFAULT_INGREDIENT_REPORT_LIMIT,
  DEFAULT_INGREDIENT_RULES_VERSION,
  DEFAULT_INGREDIENT_PRODUCT_GENERATION_METHOD,
  DEFAULT_PROFILE_CANDIDATE_LIMIT,
  DEFAULT_PROFILE_REVIEW_LIMIT,
  DEFAULT_RECIPE_INGEST_GENERATION_METHOD,
  DEFAULT_RECIPE_INGEST_LIMIT,
  DEFAULT_RECIPE_INGEST_RULES_VERSION,
  DEFAULT_RECIPE_EXTRACTION_GENERATION_METHOD,
  DEFAULT_RECIPE_EXTRACTION_LIMIT,
  DEFAULT_RECIPE_EXTRACTION_RULES_VERSION,
  PROMOTION_METHOD,
  PROMOTION_RULES_VERSION,
  DEFAULT_RECIPE_PROFILE_CANDIDATE_LIMIT,
  DEFAULT_RECIPE_PROFILE_REVIEW_LIMIT,
  DEFAULT_RECIPE_GENERATION_METHOD,
  DEFAULT_RECIPE_RULES_VERSION,
  MAPPING_SUGGESTION_METHOD,
  PROFILE_CANDIDATE_METHOD,
  PROFILE_CANDIDATE_RULES_VERSION,
  RECIPE_NUTRITION_PROFILE_METHOD,
  RECIPE_NUTRITION_PROFILE_RULES_VERSION,
  RECIPE_EXTRACTION_PROMPT_VERSION,
  DEFAULT_USER_FOOD_PROFILE_GENERATION_METHOD,
  DEFAULT_USER_FOOD_PROFILE_RULES_VERSION,
  DEFAULT_EVENT_SCORES,
  SUPPORTED_PROFILE_REVIEW_DECISIONS,
  SUPPORTED_PROMOTION_DECISIONS,
  SUPPORTED_RECIPE_FEEDBACK_EVENT_TYPES,
  SUPPORTED_RECIPE_FEEDBACK_EXTRACTION_METHODS,
  SUPPORTED_RECIPE_FEEDBACK_POLARITIES,
  SUPPORTED_RECIPE_FEEDBACK_SIGNAL_TYPES,
  SUPPORTED_RECIPE_FEEDBACK_SOURCES,
  SUPPORTED_USER_FOOD_PROFILE_REVIEW_STATUSES,
  SUPPORTED_USER_FOOD_CONSTRAINT_TYPES,
  SUPPORTED_USER_FOOD_TARGET_TYPES,
  SUPPORTED_USER_FOOD_CONSTRAINT_SEVERITIES,
  SUPPORTED_USER_FOOD_PREFERENCE_TYPES,
  SUPPORTED_USER_FOOD_PREFERENCE_SOURCES,
  SUPPORTED_RECIPE_INGEST_JOB_STATUSES,
  SUPPORTED_RECIPE_PROFILE_REVIEW_DECISIONS,
  SUPPORTED_INGREDIENT_REVIEW_STATUSES,
  INGREDIENT_PRODUCT_MAPPING_TYPES,
  INGREDIENT_PRODUCT_REVIEW_STATUSES,
  DEFAULT_RECIPE_QUALITY_REPORT_LIMIT,
  DEFAULT_MEAL_PLAN_DAYS,
  DEFAULT_MEALS_PER_DAY,
  MEAL_PLAN_REQUIREMENTS_GENERATION_METHOD,
  MEAL_PLAN_REQUIREMENTS_RULES_VERSION,
  MEAL_PLAN_NET_REQUIREMENTS_GENERATION_METHOD,
  MEAL_PLAN_NET_REQUIREMENTS_RULES_VERSION,
  MEAL_PLAN_PRODUCT_CANDIDATE_GENERATION_METHOD,
  MEAL_PLAN_PRODUCT_CANDIDATE_RULES_VERSION,
  MEAL_PLAN_BASKET_OPTIMIZER_GENERATION_METHOD,
  MEAL_PLAN_BASKET_OPTIMIZER_RULES_VERSION,
  MEAL_PLAN_BASKET_OPTIMIZER_VERSION,
  MEAL_PLAN_SHOPPING_ORCHESTRATION_GENERATION_METHOD,
  MEAL_PLAN_SHOPPING_ORCHESTRATION_RULES_VERSION,
  SUPPORTED_RECIPE_REVIEW_STATUSES,
  SUPPORTED_RECIPE_QUALITY_STATUSES,
  SUPPORTED_RECIPE_READINESS_STATUSES,
  SUPPORTED_RECIPE_USABILITY_STATUSES,
  SUPPORTED_MEAL_PLAN_MEAL_TYPES,
  SUPPORTED_MEAL_PLAN_REQUIREMENT_ADAPTER_STATUSES,
  SUPPORTED_MEAL_PLAN_NET_INVENTORY_STATUSES,
  SUPPORTED_MEAL_PLAN_NET_REQUIREMENT_ADAPTER_STATUSES,
  SUPPORTED_MEAL_PLAN_PRODUCT_CANDIDATE_STATUSES,
  SUPPORTED_MEAL_PLAN_OPTIMIZED_BASKET_ITEM_STATUSES,
  SUPPORTED_MEAL_PLAN_SHOPPING_RUN_STATUSES,
  SUPPORTED_STAGED_INGREDIENT_REVIEW_STATUSES,
  SUPPORTED_STAGED_RECIPE_REVIEW_STATUSES,
  SUPPORTED_MAPPING_REVIEW_DECISIONS,
  readCsvRows,
  registerSourceFiles,
  createCanonicalIngredient,
  createUserFoodProfile,
  createUserInventory,
  createRecipeIngestJob,
  addUserFoodConstraint,
  addOrUpdateUserFoodPreference,
  addOrUpdateUserEquipment,
  aggregateFeedbackSummaryByProfile,
  aggregateFeedbackSummaryByRecipe,
  attachManualNoteSignals,
  buildTasteProfileConfidence,
  appendRecipePromotionHistory,
  deleteCanonicalIngredient,
  deleteRecipeFeedbackEvent,
  deleteUserFoodProfile,
  deleteUserInventory,
  deleteCanonicalRecipe,
  deleteRecipeIngestStaging,
  getCanonicalIngredientById,
  getLatestFeedbackForProfileAndRecipe,
  getRecipeFeedbackById,
  getRecipeFeedbackSignalById,
  getUserFoodProfileBundle,
  getUserFoodProfileById,
  getUserFoodProfileByUserId,
  getIngredientByKey,
  getIngredientsByKeys,
  getRecipeById,
  getRecipeByKey,
  getRecipeDetail,
  getInventoryItemById,
  getOrCreateUserInventoryByUserId,
  getUserInventoryById,
  getUserInventoryByUserId,
  hydrateIngredientRow,
  hydrateInventoryItemRow,
  hydrateRecipeFeedbackEventRow,
  hydrateRecipeFeedbackSignalRow,
  hydrateTasteProfileSignalSourceRow,
  hydrateTasteProfileSnapshotRow,
  hydrateUserInventoryRow,
  hydrateMealPlanOptimizedBasketItemRow,
  hydrateMealPlanOptimizedBasketRow,
  hydrateRecipeNutritionProfileCandidateRow,
  assignRecipeNutritionConfidence,
  buildIngredientFilter,
  buildIngredientInspectionReport,
  buildIngredientNutritionProfileId,
  buildIngredientNutritionProfileCandidates,
  buildIngredientProductMappingId,
  buildIngredientProductMappingSuggestions,
  buildIngredientGapId,
  buildProductCandidateId,
  buildProductCandidates,
  buildRecipeFeedbackId,
  buildRecipeFeedbackSignalId,
  buildRecipeFeedbackSummary,
  buildUserTasteProfileSignalSourceId,
  buildUserTasteProfileSnapshot,
  buildUserTasteProfileSnapshotId,
  buildUserTasteProfileSnapshots,
  buildUserEquipmentId,
  buildUserFoodConstraintId,
  buildUserFoodPreferenceId,
  buildUserFoodProfileId,
  buildPromotionHistoryId,
  buildRecipeIngestJobId,
  buildRecipeExtractionPrompt,
  buildRecipeNutritionProfileId,
  buildRecipeNutritionProfileCandidateId,
  buildRecipeNutritionProfileCandidates,
  buildRecipeQualityReport,
  buildRecipeProfileReviewEventId,
  buildMealPlanId,
  buildMealPlanItemId,
  buildMealPlanKey,
  buildInventoryIdentityKey,
  buildInventoryItemId,
  buildUserInventoryId,
  buildUserInventoryKey,
  buildMealPlanRequirementId,
  buildMealPlanRequirementItemId,
  buildMealPlanRequirementKey,
  buildMealPlanNetRequirementId,
  buildMealPlanNetRequirementItemId,
  buildMealPlanNetRequirementKey,
  buildMealPlanProductCandidateId,
  buildMealPlanProductCandidateSetId,
  buildMealPlanProductCandidateSetKey,
  buildMealPlanOptimizedBasketId,
  buildMealPlanOptimizedBasketItemId,
  buildMealPlanOptimizerRunKey,
  buildMealPlanShoppingRunId,
  buildMealPlanShoppingRunKey,
  buildMealPlanShoppingRunRecord,
  buildMealTargets,
  buildFallbackTasteProfile,
  buildSyntheticBasketPlan,
  buildSyntheticPriceLookup,
  buildStagedRecipeBundleFromExtraction,
  buildStagedRecipeId,
  buildProfileReviewEventId,
  buildRecommendedIngredientReviewTargets,
  fetchApprovedMappingsWithMacroNutrients,
  fetchRecipeIngestJobs,
  fetchRecipeNutritionProfileSourceRows,
  fetchStagedRecipesForJob,
  generateIngredientNutritionProfileCandidates,
  generateRecipeNutritionProfileCandidates,
  mergeDuplicateInventoryItems,
  getRecipePromotionCandidateDetail,
  getIngredientNutritionProfileCandidateDetail,
  getRecipeNutritionProfileCandidateDetail,
  getStagedRecipeDetail,
  getStagedRecipeDetailByJobId,
  insertStagedRecipeBundle,
  isRecipeExtractionLlmConfigured,
  insertProductCandidate,
  insertProductCandidates,
  listIngredientsByReviewStatus,
  listFeedbackByProfileId,
  listFeedbackByRecipeId,
  listInventoryItems,
  listUserEquipment,
  listUserFoodConstraints,
  listUserFoodPreferences,
  listUserTasteProfileSignalSources,
  listUserTasteProfileSnapshots,
  listApprovedIngredientNutritionProfiles,
  listIngredientProductMappingsByIngredient,
  listProductsByIngredient,
  listApprovedRecipeNutritionProfiles,
  listIngredientNutritionProfileCandidatesForReview,
  listRecipeNutritionProfileCandidatesForReview,
  listRecipePromotionCandidates,
  listRecipesByReviewStatus,
  listStagedRecipes,
  matchExtractedIngredient,
  matchExtractedIngredients,
  matchProductCandidateToIngredient,
  normalizeAliasesJson,
  normalizeIngredientKeyForRecipe,
  normalizeIngredientKey,
  normalizeIngredientReportOptions,
  normalizeIngredientRecord,
  normalizeIngredientProductMapping,
  normalizeMealPlanBasketOptimizerOptions,
  normalizeProductCandidate,
  normalizeRecipeFeedbackRecord,
  normalizeRecipeFeedbackSignalRecord,
  normalizeInventoryItemRecord,
  normalizeTasteProfileBuildOptions,
  normalizeTasteProfileSignalSourceRecord,
  normalizeTasteProfileSnapshotRecord,
  normalizeUserFoodKey,
  normalizeUserEquipmentRecord,
  normalizeUserFoodConstraintRecord,
  normalizeUserFoodPreferenceRecord,
  normalizeUserFoodProfileRecord,
  normalizeRecipeIngredientRecord,
  normalizeRecipeIngestJobRecord,
  normalizeRecipeKey,
  normalizeRecipeName,
  normalizeRecipeQualityReportOptions,
  normalizeRecipeRecord,
  normalizeRecipeStepRecord,
  normalizeRecipeNutritionProfileCandidate,
  normalizeRecipeNutritionProfileOptions,
  normalizeRecipeProfileReviewDecision,
  normalizeStagedIngredientRecord,
  normalizeStagedRecipeRecord,
  normalizeStagedStepRecord,
  parseRecipeExtractionJson,
  parseProductAttributes,
  normalizeProfileCandidateOptions,
  normalizeProfileReviewDecision,
  classifyTasteProfileConfidence,
  classifyRecipeUsability,
  computeUserTasteProfileSnapshot,
  determineRecipeReadinessStatus,
  determineAdapterStatus,
  determineInventoryStatus,
  determineNetRequirementAdapterStatus,
  determineMealPlanProductCandidateStatus,
  determineMealPlanShoppingRunStatus,
  averageSelectionScore,
  generateMealPlan,
  buildMealPlanRequirements,
  buildMealPlanNetRequirements,
  buildMealPlanProductCandidateSet,
  buildMealPlanProductCandidates,
  optimizeMealPlanBasket,
  runMealPlanShoppingOrchestration,
  getMealPlanDetail,
  getMealPlanOptimizedBasketDetail,
  getMealPlanShoppingRunDetail,
  handleGenerateMealPlanRequest,
  handleGetMealPlanOptimizedBasketRequest,
  handleGetMealPlanRequest,
  handleGetMealPlanShoppingRunRequest,
  handleRunMealPlanShoppingRequest,
  addInventoryItem,
  reduceInventoryItemQuantity,
  feedbackEventInfluence,
  normalizeMealPlanOptions,
  normalizeMealPlanRequirementOptions,
  normalizeMealPlanNetRequirementOptions,
  normalizeMealPlanProductCandidateOptions,
  normalizeMealPlanShoppingOrchestrationOptions,
  promoteStagedRecipeToCanonical,
  recordRecipeCooked,
  recordRecipeCookedAgain,
  recordRecipeDismissed,
  recordRecipeFeedbackEvent,
  recordRecipeFeedbackNote,
  recordRecipeImpression,
  recordRecipeSaved,
  recordRecipeSwipeLeft,
  recordRecipeSwipeRight,
  recordRecipeSwipeUp,
  removeInventoryItem,
  removeUserFoodConstraint,
  reviewIngredientNutritionProfileCandidate,
  reviewIngredientProductMapping,
  reviewAndPromoteRecipe,
  reviewRecipeNutritionProfileCandidate,
  requestRecipeExtraction,
  searchRecipesByNormalizedTitle,
  searchStagedRecipes,
  searchCanonicalIngredients,
  resolveCanonicalProductId,
  resolveMealPlanningApiAdapter,
  resolveMealPlanShoppingOrchestrationAdapter,
  DEFAULT_TASTE_PROFILE_BUILD_LIMIT,
  DEFAULT_TASTE_PROFILE_GENERATION_METHOD,
  DEFAULT_TASTE_PROFILE_RULES_VERSION,
  MEAL_PLAN_GENERATION_METHOD,
  MEAL_PLAN_RULES_VERSION,
  SCORE_WEIGHTS,
  STORE_LOCATION_RULES_VERSION,
  STORE_LOCATION_SOURCE,
  FEEDBACK_EVENT_INFLUENCE,
  NOTE_SIGNAL_FAMILY_MAP,
  SUPPORTED_TASTE_PROFILE_SIGNAL_FAMILIES,
  SUPPORTED_TASTE_PROFILE_SOURCE_TYPES,
  USDA_MACRO_NUTRIENTS,
  USDA_MACRO_NUTRIENT_IDS,
  USDA_REQUIRED_FILES,
  CLUSTERABLE_DATA_TYPES,
  USDA_CLUSTER_GENERATION_METHOD,
  USDA_CLUSTER_RULES_VERSION,
  listUsdaFoodClusterCandidatesByKey,
  normalizeUsdaFoodClusterCandidate,
  parseUsdaFoodDescription,
  scoreRepresentativeCandidate,
  splitUsdaDescription,
  suggestIngredientNutritionMappings,
  suggestIngredientProductMappings,
  summarizeMealPlanRequirementItems,
  summarizeMealPlanNetRequirementItems,
  summarizeMealPlanProductCandidates,
  summarizeMissingNutritionInputs,
  scoreRecipeCandidate,
  updateInventoryItemQuantity,
  updateUserFoodNutritionTargets,
  upsertIngredientGapCandidate,
  upsertSourceDataset,
  upsertIngredientNutritionMappingSuggestions,
  upsertIngredientNutritionProfileCandidates,
  upsertIngredientByKey,
  upsertIngredientProductMapping,
  upsertIngredientProductMappings,
  upsertUserFoodProfileByUserId,
  upsertRecipeByKey,
  upsertRecipeIngredients,
  upsertRecipeNutritionProfileCandidates,
  upsertRecipeSteps,
  extractRecipeJobToStaging,
  extractRecipeJobsToStaging,
  updateRecipeIngestJobStatus,
  updateStagedRecipeReviewStatus,
  aggregateMealPlanRequirementItems,
  buildInventoryCoverageIndex,
  convertPackageSizeToGrams,
  estimateShoppingQuantity,
  hydrateMealPlanOptimizedBasketItemRow,
  hydrateMealPlanOptimizedBasketRow,
  hydrateMealPlanShoppingRunRow,
  hydrateMealPlanProductCandidateRow,
  hydrateNetRequirementItemRow,
  hydrateRequirementItemRow,
  validateRecipeExtractionPayload,
  validateProfileCandidateReviewTransition,
  validateRecipeProfileCandidateReviewTransition,
  upsertUsdaFoodClusterMembers,
  upsertUsdaFoodClusters,
  upsertUsdaFoodClusterCandidates,
  upsertUsdaFoodCategories,
  upsertUsdaFoodNutrients,
  upsertUsdaFoodPortions,
  upsertUsdaFoods,
  upsertUsdaMeasureUnits,
  upsertUsdaNutrients,
  withPostgresClient,
};
