const { buildEnrichment, detectNameDrift } = require('./phase1/enrichment');
const { computeSnapshotId, computeSourceProductId } = require('./phase1/ids');
const {
  buildRawSnapshotRecord,
  importDailySnapshotFile,
  importDailySnapshotText,
  parseSnapshotRows,
} = require('./phase1/importer');
const {
  FirestoreDataBackboneStore,
  JsonFileDataBackboneStore,
  InMemoryDataBackboneStore,
  createEmptyDataBackbone,
  createRuntimeDataBackboneStore,
  getEnrichmentByFingerprint,
  resolveStoreBackend,
  storeEnrichment,
} = require('./phase1/store');
const { buildCanonicalEn } = require('./phase1_5/canonical_en');
const { buildDisplayEn, buildEnglishMetadata } = require('./phase1_5/display_builder');
const { translateDisplayEn } = require('./phase1_5/translator');
const { upgradeEnrichmentToEnglish } = require('./phase1_5/upgrade_enrichment');
const { upgradeTranslations } = require('./phase1_5/upgrade_translations');
const { aggregateCurrentPrices } = require('./phase2/aggregate');
const { detectAmbiguity } = require('./phase2/ambiguity');
const { filterCandidates, inferCategoryCodes, inferProductType } = require('./phase2/filter');
const { matchQueryAgainstState, matchSingleItem } = require('./phase2/matcher');
const { normalizeInput, parseQueryItem, splitQueryItems, tokenizeInput } = require('./phase2/normalize');
const { scoreCandidate } = require('./phase2/score');
const { handleQueryServiceRequest, queryPriceComparison } = require('./phase2/service');
const { aiDisambiguate } = require('./phase3/ai_disambiguator');
const { collectFeedback } = require('./phase3/feedback_collector');
const { generateDeterministicEmbedding, generateEmbeddingRecord } = require('./phase3/embedding_generator');
const { runEmbeddingGenerationJob, runSemanticEnrichmentJob } = require('./phase3/jobs');
const { buildSemanticProfile } = require('./phase3/semantic_enricher');
const { buildDailyAggregation } = require('./phase3_5/aggregator');
const { buildCategoryDailyAggregates } = require('./phase3_5/category_aggregator');
const { runDailyAggregation } = require('./phase3_5/job');
const { buildProductDailyPrices } = require('./phase3_5/product_aggregator');
const { getCategoryTrends, getProductHistory } = require('./phase3_5/service');
const { applyConstraintFilters } = require('./phase4/constraint_filters');
const { executeQueryPlan } = require('./phase4/query_executor');
const { parseQuery } = require('./phase4/query_parser');
const { buildQueryPlan } = require('./phase4/query_planner');
const { rankQueryResults } = require('./phase4/ranker');
const { handleQueryEngineRequest, queryEngine } = require('./phase4/service');
const { buildAnalyticsEvent, trackAnalyticsEvent, trackQueryAnalytics } = require('./phase6/analytics');
const { detectWatchlistPriceDrops, sendWatchlistAlerts } = require('./phase6/alerts');
const {
  applyEffectiveCanonicalDecisions,
  buildCanonicalDisambiguationPromptPayload,
  isLlmDisambiguationEnabled,
  parseCanonicalDisambiguationModelPayload,
  recordHumanCanonicalDisambiguationDecision,
  requestCanonicalDisambiguationBatch,
  runCanonicalDisambiguationAdjudication,
  getEffectiveCanonicalDisambiguationDecision,
  summarizeCanonicalDisambiguationReviewState,
  validateCanonicalDisambiguationDecision,
  validateCanonicalDisambiguationResponse,
} = require('./phase6/disambiguation');
const { backfillCanonicalEmbeddings, isEmbeddingApiConfigured, requestRemoteEmbedding } = require('./phase6/embeddings');
const { createFcmNotifier, isFcmConfigured } = require('./phase6/fcm');
const { chooseCandidateWithGrok, isGrokConfigured, resolveAmbiguityWithGrok } = require('./phase6/grok');
const {
  buildCanonicalDisambiguationFingerprint,
  buildCanonicalDisambiguationQueueRecord,
  buildCanonicalProductKey,
  buildCanonicalizationState,
  buildIngestRun,
  getCanonicalDisambiguationDecisionByFingerprint,
  importDailySnapshotCsvStream,
  importDailySnapshotZip,
  runCanonicalDisambiguationDryRun,
  syncCanonicalDisambiguationArtifacts,
  upsertCanonicalDisambiguationDecision,
} = require('./phase6/ingest');
const {
  buildSnapshotZipUrl,
  downloadSnapshotZip,
  listSnapshotEntries,
  openSnapshotEntryStream,
  openSnapshotEntryStreamByName,
  parseSnapshotEntryMetadata,
  resolveLatestAvailableSnapshotDate,
} = require('./phase6/kolkostruva_client');
const { runDailyProductionPipeline } = require('./phase6/jobs');
const { appendPipelineLog, createPipelineLog, recordPipelineLog } = require('./phase6/logging');
const { buildDailyIngestSchedule, shouldRunIngestForDate } = require('./phase6/scheduler');
const { rebuildDemandAggregates } = require('./phase7/aggregator');
const {
  DEMAND_EMBEDDING_MODEL,
  generateDemandEmbedding,
  rebuildDemandClusters,
  rebuildDemandEmbeddings,
} = require('./phase7/clustering');
const {
  buildDemandKey,
  buildDemandLogRecord,
  captureManualDemandFeedback,
  captureUnmatchedQuery,
} = require('./phase7/demand_logger');
const { runDemandIntelligenceJobs } = require('./phase7/jobs');
const {
  getTopDemand,
  getTrendingDemand,
  handleCantFindThisRequest,
  handleGetTopDemandRequest,
  handleGetTrendingDemandRequest,
} = require('./phase7/service');
const { DEFAULT_BASKET_LIMITS, DEFAULT_PREFERENCE_WEIGHTS } = require('./phase8/constants');
const { optimizeBasket, resolveLimits, resolvePreferences } = require('./phase8/optimizer');
const { handleOptimizeBasketRequest } = require('./phase8/service');
const {
  getTierFeatures,
  hasActivePremiumEntitlement,
  resolveUserTier,
  syncRevenueCatEntitlement,
} = require('./phase10/entitlements');
const {
  handleGetEntitlementStatusRequest,
  handleSyncRevenueCatEntitlementRequest,
} = require('./phase10/service');
const {
  buildCanonicalQueryObject,
  buildCanonicalTermRecord,
  buildSynonymRecord,
  levenshteinDistance,
  normalizeSearchText,
  tokenizeSearchText,
} = require('./phase12/canonicalization');
const {
  CATEGORY_TREE,
  ENRICHMENT_PROMPT_VERSION,
  buildEnrichmentPrompt,
  isLlmEnrichmentEnabled,
  requestCanonicalEnrichment,
  syncCanonicalEnrichmentArtifacts,
  validateEnrichmentResponse,
} = require('./phase15/enrichment');
const {
  ENRICHMENT_FILTER_FIELDS,
  LAYER_SELECTIONS,
  buildCanonicalEnrichmentAnalytics,
  getCanonicalProductViewById,
  listCanonicalProductViews,
  searchCanonicalProductViews,
} = require('./phase15/readers');
const {
  DEFAULT_PRODUCT_LAYER_MODE,
  FACET_FIELDS,
  buildProductListItem,
  handleCanonicalProductFilterFacetsRequest,
  handleGetCanonicalProductRequest,
  handleGetEnrichmentAnalyticsSummaryRequest,
  handleSearchCanonicalProductsRequest,
  resolveRequestedLayerMode,
  searchCanonicalProductCatalog,
} = require('./phase15/service');
const {
  CONFIDENCE_LEVELS,
  DEFAULT_LIMIT_PER_ITEM,
  INTERNAL_SEARCH_LIMIT,
  MAX_ITEMS_PER_REQUEST,
  MAX_LIMIT_PER_ITEM,
  RESOLUTION_STATUSES,
  SCORE_THRESHOLDS,
  handleResolveShoppingListItemsRequest,
  resolveShoppingListItems,
} = require('./phase15/shopping_list');
const {
  ALLOWED_AMBIGUOUS_POLICIES,
  ALLOWED_UNRESOLVED_POLICIES,
  DEFAULT_PLANNER_OPTIONS,
  DEFAULT_REQUESTED_QUANTITY,
  buildBasketPlanFromResolvedItems,
  handleBuildBasketPlanRequest,
} = require('./phase15/basket_planner');
const {
  ALLOWED_PRICE_MODES,
  ALLOWED_PRICE_STATUSES,
  DEFAULT_CURRENCY,
  DEFAULT_LOOKUP_OPTIONS,
  MAX_LOOKUP_IDS,
  handleLookupCanonicalProductPricesRequest,
  lookupCanonicalProductPrices,
  lookupPricesForBasketPlan,
} = require('./phase16/price_lookup');
const {
  ALLOWED_OPTIMIZER_AMBIGUOUS_POLICIES,
  ALLOWED_OPTIMIZER_STRATEGIES,
  ALLOWED_STALE_POLICIES,
  DEFAULT_OPTIMIZER_OPTIONS,
  buildBasketOptimizationExplanation,
  handleOptimizeBasketSingleStoreRequest,
  normalizeOptimizerOptions,
  optimizeBasketMultiStore,
  optimizeBasketSingleStore,
} = require('./phase16/basket_optimizer');
const {
  runSearchQualityFeedbackLoop,
  seedSearchQualityDefaults,
} = require('./phase12/feedback_loop');
const {
  buildWatchlistSummary,
  getWatchlistInsights,
  runWatchlistDailyEvaluation,
  setTargetPrice,
} = require('./phase9/intelligence');
const { runDailyWatchlistIntelligence, runWeeklyIntervalRecompute } = require('./phase9/jobs');
const { recomputeWatchlistRecurringPatterns } = require('./phase9/recurrence');
const {
  handleSetTargetPriceRequest,
  handleWatchlistInsightsRequest,
  handleWatchlistSummaryRequest,
} = require('./phase9/service');
const { syncFirestoreToSQL } = require('./sync/firestore_to_sql');
const { syncFirestoreToVector } = require('./sync/firestore_to_vector');
const { runSyncJobs } = require('./sync/jobs');
const {
  buildPostgresConfig,
  checkPostgresHealth,
  createPostgresPool,
  isPostgresConfigured,
  withPostgresClient,
} = require('./db/postgres');
const {
  checksumSql,
  ensureSchemaMigrationsTable,
  listMigrationFiles,
  loadAppliedMigrations,
  resolveDefaultMigrationsDir,
  runPostgresMigrations,
} = require('./db/migrations');
const {
  completeImportBatch,
  createImportBatch,
  getImportBatch,
  getSourceDataset,
  insertSourceFile,
  normalizeDataset,
  normalizeImportBatch,
  normalizeSourceFile,
  upsertSourceDataset,
} = require('./db/import_metadata_repository');
const {
  USDA_MACRO_NUTRIENTS,
  USDA_MACRO_NUTRIENT_IDS,
  isUsdaMacroNutrientId,
} = require('./db/usda/macro_constants');
const {
  isCompleteCsvRecord,
  parseCsvRecord,
  readCsvRows,
} = require('./db/usda/csv_stream');
const {
  USDA_REQUIRED_FILES,
  buildUsdaDatasetId,
  resolveUsdaDatasetRoot,
  resolveUsdaFilePaths,
} = require('./db/usda/usda_schema');
const {
  completeUsdaImportRun,
  createUsdaImportRun,
  getUsdaFoodWithMacros,
  normalizeFood,
  normalizeFoodCategory,
  normalizeFoodNutrient,
  normalizeFoodPortion,
  normalizeMeasureUnit,
  normalizeNutrient,
  normalizeUsdaImportRun,
  upsertUsdaFoodCategories,
  upsertUsdaFoodNutrients,
  upsertUsdaFoodPortions,
  upsertUsdaFoods,
  upsertUsdaMeasureUnits,
  upsertUsdaNutrients,
} = require('./db/usda/usda_repository');
const {
  checksumFile,
  importCsvInBatches,
  importUsdaMacros,
  inspectSourceFile,
  registerSourceFiles,
} = require('./db/usda/usda_importer');
const {
  MEAL_ACTIVE_STATUSES,
  MEAL_DEFAULT_PRICE_FALLBACK_CONFIDENCE,
  MEAL_MAPPING_TYPES,
  MEAL_MAPPING_TYPE_PRIORITIES,
  MEAL_RUNTIME_SAFE_INGREDIENT_FIELDS,
  MEAL_SUPPORTED_LOCALES,
  MEAL_UNIT_TYPES,
} = require('./meal/shared/constants');
const {
  buildIngredientCategoryRecord,
  buildIngredientFamilyRecord,
  buildIngredientRecord,
  getIngredientById,
  getIngredientCategoryById,
  getIngredientFamilyById,
  listIngredientCategories,
  listIngredientFamilies,
  listIngredients,
  upsertIngredient,
  upsertIngredientCategory,
  upsertIngredientFamily,
} = require('./meal/catalog/service');
const {
  buildIngredientPurchaseDemand,
  buildIngredientUnitRuleRecord,
  buildUnitConversionRecord,
  buildUnitRecord,
  convertEdibleQuantityToPurchase,
  convertIngredientQuantityToEdible,
  convertUnitValue,
  getIngredientUnitRuleByIngredientId,
  getUnitById,
  listUnits,
  seedDefaultMealUnits,
  upsertIngredientUnitRule,
  upsertUnit,
  upsertUnitConversion,
} = require('./meal/units/service');
const {
  buildProductIngredientMappingRecord,
  estimateIngredientCost,
  listIngredientPriceCandidates,
  listProductIngredientMappings,
  resolveBestProductIngredientMapping,
  upsertProductIngredientMapping,
} = require('./meal/bridge/service');

module.exports = {
  ALLOWED_AMBIGUOUS_POLICIES,
  ALLOWED_UNRESOLVED_POLICIES,
  ALLOWED_PRICE_MODES,
  ALLOWED_PRICE_STATUSES,
  ALLOWED_OPTIMIZER_AMBIGUOUS_POLICIES,
  ALLOWED_OPTIMIZER_STRATEGIES,
  ALLOWED_STALE_POLICIES,
  aggregateCurrentPrices,
  aiDisambiguate,
  appendPipelineLog,
  applyConstraintFilters,
  backfillCanonicalEmbeddings,
  applyEffectiveCanonicalDecisions,
  buildAnalyticsEvent,
  buildBasketOptimizationExplanation,
  buildBasketPlanFromResolvedItems,
  buildCanonicalQueryObject,
  buildCanonicalTermRecord,
  buildCategoryDailyAggregates,
  buildCanonicalEn,
  buildCanonicalDisambiguationFingerprint,
  buildCanonicalDisambiguationPromptPayload,
  buildCanonicalDisambiguationQueueRecord,
  buildCanonicalProductKey,
  buildDailyAggregation,
  buildDailyIngestSchedule,
  buildDemandKey,
  buildDemandLogRecord,
  buildDisplayEn,
  buildCanonicalizationState,
  buildSynonymRecord,
  buildEnglishMetadata,
  buildEnrichment,
  buildIngestRun,
  buildProductDailyPrices,
  buildQueryPlan,
  buildRawSnapshotRecord,
  buildSemanticProfile,
  buildSnapshotZipUrl,
  buildWatchlistSummary,
  captureManualDemandFeedback,
  captureUnmatchedQuery,
  chooseCandidateWithGrok,
  collectFeedback,
  computeSnapshotId,
  computeSourceProductId,
  createEmptyDataBackbone,
  createFcmNotifier,
  createPipelineLog,
  CATEGORY_TREE,
  CONFIDENCE_LEVELS,
  DEFAULT_BASKET_LIMITS,
  DEFAULT_CURRENCY,
  DEFAULT_LIMIT_PER_ITEM,
  DEFAULT_LOOKUP_OPTIONS,
  DEFAULT_OPTIMIZER_OPTIONS,
  DEFAULT_PLANNER_OPTIONS,
  DEFAULT_PRODUCT_LAYER_MODE,
  DEFAULT_PREFERENCE_WEIGHTS,
  DEFAULT_REQUESTED_QUANTITY,
  DEMAND_EMBEDDING_MODEL,
  ENRICHMENT_FILTER_FIELDS,
  detectAmbiguity,
  detectNameDrift,
  detectWatchlistPriceDrops,
  downloadSnapshotZip,
  executeQueryPlan,
  FACET_FIELDS,
  FirestoreDataBackboneStore,
  filterCandidates,
  generateDemandEmbedding,
  generateDeterministicEmbedding,
  generateEmbeddingRecord,
  getCanonicalDisambiguationDecisionByFingerprint,
  getCanonicalProductViewById,
  getEffectiveCanonicalDisambiguationDecision,
  getEnrichmentByFingerprint,
  getTierFeatures,
  getCategoryTrends,
  getProductHistory,
  getTopDemand,
  getTrendingDemand,
  getWatchlistInsights,
  handleBuildBasketPlanRequest,
  handleLookupCanonicalProductPricesRequest,
  handleOptimizeBasketSingleStoreRequest,
  handleResolveShoppingListItemsRequest,
  handleCanonicalProductFilterFacetsRequest,
  handleGetCanonicalProductRequest,
  handleGetEntitlementStatusRequest,
  handleCantFindThisRequest,
  handleGetEnrichmentAnalyticsSummaryRequest,
  handleGetTopDemandRequest,
  handleGetTrendingDemandRequest,
  handleOptimizeBasketRequest,
  handleQueryEngineRequest,
  handleQueryServiceRequest,
  handleSearchCanonicalProductsRequest,
  handleSetTargetPriceRequest,
  handleSyncRevenueCatEntitlementRequest,
  handleWatchlistInsightsRequest,
  handleWatchlistSummaryRequest,
  hasActivePremiumEntitlement,
  importDailySnapshotCsvStream,
  importDailySnapshotFile,
  importDailySnapshotText,
  importDailySnapshotZip,
  inferCategoryCodes,
  inferProductType,
  InMemoryDataBackboneStore,
  isEmbeddingApiConfigured,
  isFcmConfigured,
  isGrokConfigured,
  isLlmEnrichmentEnabled,
  isLlmDisambiguationEnabled,
  INTERNAL_SEARCH_LIMIT,
  JsonFileDataBackboneStore,
  levenshteinDistance,
  LAYER_SELECTIONS,
  listCanonicalProductViews,
  lookupCanonicalProductPrices,
  lookupPricesForBasketPlan,
  matchQueryAgainstState,
  matchSingleItem,
  MAX_ITEMS_PER_REQUEST,
  MAX_LOOKUP_IDS,
  MAX_LIMIT_PER_ITEM,
  listSnapshotEntries,
  normalizeInput,
  normalizeOptimizerOptions,
  normalizeSearchText,
  openSnapshotEntryStream,
  openSnapshotEntryStreamByName,
  optimizeBasket,
  optimizeBasketMultiStore,
  optimizeBasketSingleStore,
  parseQuery,
  parseQueryItem,
  parseCanonicalDisambiguationModelPayload,
  parseSnapshotRows,
  queryEngine,
  queryPriceComparison,
  rankQueryResults,
  recordHumanCanonicalDisambiguationDecision,
  recordPipelineLog,
  parseSnapshotEntryMetadata,
  resolveStoreBackend,
  rebuildDemandAggregates,
  rebuildDemandClusters,
  rebuildDemandEmbeddings,
  recomputeWatchlistRecurringPatterns,
  requestRemoteEmbedding,
  requestCanonicalEnrichment,
  requestCanonicalDisambiguationBatch,
  resolveUserTier,
  resolveAmbiguityWithGrok,
  resolveLatestAvailableSnapshotDate,
  resolveRequestedLayerMode,
  resolveLimits,
  resolvePreferences,
  resolveShoppingListItems,
  RESOLUTION_STATUSES,
  runCanonicalDisambiguationAdjudication,
  runCanonicalDisambiguationDryRun,
  runDailyAggregation,
  runDailyProductionPipeline,
  runDailyWatchlistIntelligence,
  runDemandIntelligenceJobs,
  runEmbeddingGenerationJob,
  runSemanticEnrichmentJob,
  runSearchQualityFeedbackLoop,
  runSyncJobs,
  runWatchlistDailyEvaluation,
  runWeeklyIntervalRecompute,
  scoreCandidate,
  SCORE_THRESHOLDS,
  searchCanonicalProductViews,
  searchCanonicalProductCatalog,
  seedSearchQualityDefaults,
  sendWatchlistAlerts,
  setTargetPrice,
  shouldRunIngestForDate,
  storeEnrichment,
  buildPostgresConfig,
  buildProductListItem,
  buildCanonicalEnrichmentAnalytics,
  checkPostgresHealth,
  checksumSql,
  completeImportBatch,
  createImportBatch,
  createPostgresPool,
  splitQueryItems,
  syncCanonicalEnrichmentArtifacts,
  summarizeCanonicalDisambiguationReviewState,
  syncCanonicalDisambiguationArtifacts,
  syncFirestoreToSQL,
  syncFirestoreToVector,
  tokenizeInput,
  tokenizeSearchText,
  trackAnalyticsEvent,
  trackQueryAnalytics,
  translateDisplayEn,
  syncRevenueCatEntitlement,
  ENRICHMENT_PROMPT_VERSION,
  upsertCanonicalDisambiguationDecision,
  upsertIngredient,
  upsertIngredientCategory,
  upsertIngredientFamily,
  upsertIngredientUnitRule,
  upsertProductIngredientMapping,
  upsertUnit,
  upsertUnitConversion,
  createRuntimeDataBackboneStore,
  ensureSchemaMigrationsTable,
  getImportBatch,
  getSourceDataset,
  insertSourceFile,
  isPostgresConfigured,
  listMigrationFiles,
  loadAppliedMigrations,
  normalizeDataset,
  normalizeImportBatch,
  normalizeSourceFile,
  validateCanonicalDisambiguationDecision,
  validateCanonicalDisambiguationResponse,
  validateEnrichmentResponse,
  upgradeEnrichmentToEnglish,
  upgradeTranslations,
  buildEnrichmentPrompt,
  resolveDefaultMigrationsDir,
  runPostgresMigrations,
  buildIngredientCategoryRecord,
  buildIngredientFamilyRecord,
  buildIngredientPurchaseDemand,
  buildIngredientRecord,
  buildIngredientUnitRuleRecord,
  buildProductIngredientMappingRecord,
  buildUnitConversionRecord,
  buildUnitRecord,
  convertEdibleQuantityToPurchase,
  convertIngredientQuantityToEdible,
  convertUnitValue,
  estimateIngredientCost,
  getIngredientById,
  getIngredientCategoryById,
  getIngredientFamilyById,
  getIngredientUnitRuleByIngredientId,
  getUnitById,
  listIngredientCategories,
  listIngredientFamilies,
  listIngredientPriceCandidates,
  listIngredients,
  listProductIngredientMappings,
  listUnits,
  MEAL_ACTIVE_STATUSES,
  MEAL_DEFAULT_PRICE_FALLBACK_CONFIDENCE,
  MEAL_MAPPING_TYPES,
  MEAL_MAPPING_TYPE_PRIORITIES,
  MEAL_RUNTIME_SAFE_INGREDIENT_FIELDS,
  MEAL_SUPPORTED_LOCALES,
  MEAL_UNIT_TYPES,
  resolveBestProductIngredientMapping,
  seedDefaultMealUnits,
  upsertSourceDataset,
  withPostgresClient,
};
