const DEFAULT_WATCHLIST_COOLDOWN_DAYS = 3;
const DEFAULT_GOOD_DEAL_THRESHOLD = 0.93;
const DEFAULT_SIGNIFICANT_DROP_PERCENT = 5;
const DEFAULT_SIGNIFICANT_DROP_AMOUNT = 0.2;

module.exports = {
  DEFAULT_GOOD_DEAL_THRESHOLD,
  DEFAULT_SIGNIFICANT_DROP_AMOUNT,
  DEFAULT_SIGNIFICANT_DROP_PERCENT,
  DEFAULT_WATCHLIST_COOLDOWN_DAYS,
};
